### ISSUE TITLE
Stuck on Loading Data Screen

### ISSUE THREAD

**Issue by maddeuce** [home-assistant/frontend#10630]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After upgrading to core 2021.11.3 & 2021.11.4 my hassio is stuck on Loading Data screen.  Its on Hassio APK, Browser (chrome/firefox/explorer), and FKB.  Only way I can get into hassio is via a hard reset on my machine.  Problem first pop up after upgrade to core 2021.11.3

### Describe the behavior you expected

1. I can gain access if I do a hard reset on my VM.
2. Doing soft reset will again get hassio to be stuck on loading data screen (with MarineDB running).
3. If I turn off MarineDB and do a soft reset inside hassio it be not be stuck, however once pass 12:00am midnight it will again be stuck at loading data screen.

There is no error on both supervisor and core log.

### Steps to reproduce the issue

see above

### What version of Home Assistant Core has the issue?

2021.11.4

**Comment by maddeuce** [comment]
Thank you for the reply.  How should I go about getting this browser console logs?

**Comment by bramkragten** [comment]
If you are using chrome:

https://developer.chrome.com/docs/devtools/open/#console

**Comment by maddeuce** [comment]
Below is the browser console log when stuck at loading data (with MariaDB on)
Uncaught (in promise) Object
config-template-card.js:329 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
(anonymous) @ config-template-card.js:329
kiosk-mode.js:16 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'shadowRoot')
    at new e (kiosk-mode.js:16)
    at kiosk-mode.js:66
card-mod.js:1 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
(anonymous) @ card-mod.js:1
slider-entity-row.js:1 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
(anonymous) @ slider-entity-row.js:1
swipe-navigation.js:18 Uncaught TypeError: Cannot read properties of null (reading 'shadowRoot')
    at swipe-navigation.js:18
atomic-calendar-revive.js:177 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
(anonymous) @ atomic-calendar-revive.js:177
DevTools failed to load source map: Could not load content for chrome-extension://jpdapbcmfllbpojmkefcikllfeoahglb/content_start/bundle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://jpdapbcmfllbpojmkefcikllfeoahglb/content_wrap/bundle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

This is browser console log with MariaDB turn off. (Does not get stuck except after 12:00 am)
ha-icon.ts:374 Icon mdi:cellphone-android was renamed to mdi:cellphone, please change your config, it will be removed in version 2021.12.
value @ ha-icon.ts:374
config-template-card.js:329 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
(anonymous) @ config-template-card.js:329
card-mod.js:1 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
(anonymous) @ card-mod.js:1
slider-entity-row.js:1 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
(anonymous) @ slider-entity-row.js:1
atomic-calendar-revive.js:177 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
(anonymous) @ atomic-calendar-revive.js:177
9card-mod.js:1 Uncaught (in promise) DOMException: Failed to execute 'querySelectorAll' on 'Element': '0' is not a valid selector.
    at it (http://192.168.100.2:8123/hacsfiles/lovelace-card-mod/card-mod.js:1:17590)
    at async HTMLElement._connect (http://192.168.100.2:8123/hacsfiles/lovelace-card-mod/card-mod.js:1:21422)
DevTools failed to load source map: Could not load content for chrome-extension://jpdapbcmfllbpojmkefcikllfeoahglb/content_start/bundle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by maddeuce** [comment]
new development now even soft restart take over 5 min to start, where just 2 hours ago soft restart take only around 45 seconds.

**Comment by bramkragten** [comment]
Start by removing all custom cards

**Comment by maddeuce** [comment]
Look like is MariaDB acting up.  I uninstalled MariaDB cleared the its log history, reinstall MariaDB back as current everything seem to got back to normal.  Maybe between recent update and with the DST issue back in version 2021.11.1 it probably missed up some of MariaDB database.  Regardless still thank you for your help.

**Comment by maddeuce** [comment]
ok spoke too soon.  Same thing happen again after 00:00 everything got stuck at loading data screen at 00:00 (12:00am).  I even set my main page to a blank page with no cards inside, and still that page got stuck on loading data screen.  To gain access I need to do a hard reset.

**Comment by bramkragten** [comment]
You should remove the custom resources, not the cards that use those resources

**Comment by maddeuce** [comment]
I'll try it tonight.  However what I don't understand is after do an hard reset everything seem to working just fine.  Then everything gone to crap after 00:00.  If its a custom resources card issue wouldn't it happen all the time?

**Comment by maddeuce** [comment]
It seems to me somewhere there data corruption and is unable to pull up new log on start of a new day.

**Comment by maddeuce** [comment]
All custom resource turn off with Mariadb turn on - stuck on loading data
![image](https://user-images.githubusercontent.com/54375636/142244555-86f35d4c-824c-4710-ac5a-a8f836034c20.png)
All custom resource turn off + Mariadb turn off. - Not stuck on loading data
![image](https://user-images.githubusercontent.com/54375636/142246013-e9bb734c-d9ff-47f0-b824-81597a1cbf91.png)

For above it doesn't seem like custom resources are causing the issue, seem like mariadb.  However there an weird issue I forgot to mention.  After I done an hard reset to gain access after midnight stuck issue, even if hassio is stuck at loading data screen like picture 1.  All my background automation still work in the background I just can't get into my dash screen.  However the loading data screen stuck after midnight doesn't act the same way,  all my automation stop working as if hassio never was on.   I think this issue is worst then stuck just on loading data screen.

**Comment by maddeuce** [comment]
At 12:00 am with Mariadb turn off dash screen is stuck, and if I press refresh page it will be stuck at loading data screen.
![image](https://user-images.githubusercontent.com/54375636/142384185-0e6ee545-0596-4df3-8401-38062b77b074.png)

**Comment by maddeuce** [comment]
Been 2 weeks can someone please help.

**Comment by spacegaier** [comment]
So from your last comments it sounds more like a DB / backend issue, rather than a frontend one, if all automations suddenly stop. If the backend does not work, then the frontend cannot show anything other than "Loading data".

Do you monitor your hardware resources, e.g. could it be that the box that HA is running on runs of of disk space or memory (although it would be weird if that always happens exactly at midnight).

Did you check your HA log files (including `home-assistant.log.fault`)? Perhaps it might make sense to increase the HA log level before the error usually appears to see if that leads to more info.
