### ISSUE TITLE
Flux in mired mode not working with Philips Hue in 2021.12

### ISSUE THREAD

**Issue by fabianschaefer** [home-assistant/frontend#11029]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since updating to Version 2021.12.5 (I directly updated to .5 from the last major release) Flux stopped working in mired mode. I suspect this issue was caused by one of the Philips Hue changes in this release. This is my Flux config:
```
switch:
  - platform: flux
    lights:
      - light.bedroom
    name: bedroom_flux
    disable_brightness_adjust: true
    mode: mired
    transition: 5
```
When I change the mode to xy, it works as expected, but I have to rely on the mired mode since not all my lamps support xy:
`mode: xy`

In the logs I see the following entries concerning this problem:
```
Logger: homeassistant.core
Source: components/hue/bridge.py:117 
First occurred: 26. Dezember 2021, 23:12:35 (38 occurrences) 
Last logged: 00:33:09

Error executing service: <ServiceCall light.turn_on (c:a377793f3fcc94ca2e7f6b03ada72aaa): entity_id=['light.bedroom'], params=color_temp=526, transition=5.0>

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1511, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 494, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/components/hue/v2/group.py", line 177, in async_turn_on
    await self.bridge.async_request_call(
  File "/usr/src/homeassistant/homeassistant/components/hue/bridge.py", line 117, in async_request_call
    return await task(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiohue/v2/controllers/lights.py", line 80, in set_state
    await self.update(id, update_obj)
  File "/usr/local/lib/python3.9/site-packages/aiohue/v2/controllers/base.py", line 146, in update
    await self._bridge.request("put", endpoint, json=data)
  File "/usr/local/lib/python3.9/site-packages/aiohue/v2/__init__.py", line 182, in request
    resp.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://192.168.2.101/clip/v2/resource/light/cbf2251c-3119-406f-bd25-4661869d417c')
```

### Describe the behavior you expected

The lights are expected to change color temperature depending on the position of the sun, but they just stay the same.

### Steps to reproduce the issue

1. Configure a Philips Hue Lamp that supports color temperatures
2. Configure a Flux switch for that lamp in the configuration.yaml file (see code snipped above)
3. Restart HA
4. Turn the Flux switch on
5. See the Logs for error messages
...

### What version of Home Assistant Core has the issue?

2021.12.5

### What was the last working version of Home Assistant Core?

2021.11

### In which browser are you experiencing the issue with?

Safari

### Which operating system are you using to run this browser?

macOS Big Sur

**Comment by fabianschaefer** [comment]
It seems that this issue only exists during night times when the mireds are very high (>500). It looks like the light.turn_on action only allows values up to 500 but Flux returns values over 500. this has either be changed or the hue integration didn‘t care about higher values in the past.

**Comment by fabianschaefer** [comment]
I noticed that I posted this issue in the wrong repo. It actually belongs to the core. I opened a new issue there: https://github.com/home-assistant/core/issues/62842
