### ISSUE TITLE
Shelly plus login

### ISSUE THREAD

**Issue by CatMonster** [home-assistant/frontend#11110]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Unable to add shelly 1PM plus, probably shelly 1PM also.
Old shelly os to restrict access with login it used to have username and password, on the new os on plus versions there is no username, only password.
Adding shelly from frontend it requires to fill username and password, but new os does not have username.

### Describe the behavior you expected

Adding shelly and omitting shelly username

### Steps to reproduce the issue

1. Enable shelly 1PM PLUS/1 PLUS password
2. Add integration/shelly
3. Add shelly, and put username/password

![image](https://user-images.githubusercontent.com/13244343/148398525-6aa1185d-ce8f-4c21-b85f-b50a7f1e2bc1.png)

### What version of Home Assistant Core has the issue?

core-2021.12.8

### Javascript errors shown in your browser console/inspector

```txt
Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/shelly/config_flow.py", line 150, in async_step_credentials
    device_info = await validate_input(
  File "/usr/src/homeassistant/homeassistant/components/shelly/config_flow.py", line 59, in validate_input
    rpc_device = await RpcDevice.create(
  File "/usr/local/lib/python3.9/site-packages/aioshelly/rpc_device.py", line 58, in create
    await instance.initialize()
  File "/usr/local/lib/python3.9/site-packages/aioshelly/rpc_device.py", line 93, in initialize
    await asyncio.gather(
  File "/usr/local/lib/python3.9/site-packages/aioshelly/rpc_device.py", line 133, in update_config
    self._config = await self._wsrpc.call("Shelly.GetConfig")
  File "/usr/local/lib/python3.9/site-packages/aioshelly/wsrpc.py", line 234, in call
    raise JSONRPCError(code, msg)
aioshelly.exceptions.JSONRPCError: (401, '{"auth_type": "digest", "nonce": 1641477985, "nc": 1, "realm": "shellyplus1pm-44179394b00c", "algorithm": "SHA-256"}')
```

**Comment by spacegaier** [comment]
The content/fields of those configuration dialogs are defined by the backend, the frontend just renders them as requested, so I will transfer the issue to the backend.
