### ISSUE TITLE
Renameing a device Fails

### ISSUE THREAD

**Issue by grillp** [home-assistant/frontend#11558]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I try an rename any device using the UI, When I press 'update' the button goes grey and the 'Name' field becomes 'locked', but the name of the device doe snot get updated.
If I reload the Device details, the old name persists 

### Describe the behavior you expected

I expect the Device to be renamed.

### Steps to reproduce the issue

1. Navigate to any device
2. Press the Pencil next to the device name
3. Type a New Name in the name field
<img width="617" alt="Screen Shot 2022-02-05 at 9 46 39 pm" src="https://user-images.githubusercontent.com/122615/152639029-e04b89e1-d34a-4556-814c-61f0111eafd9.png">
4. Press Update
<img width="606" alt="Screen Shot 2022-02-05 at 9 45 13 pm" src="https://user-images.githubusercontent.com/122615/152639022-bee6e141-c221-4276-ba25-fb27010bbaf8.png">

### What version of Home Assistant Core has the issue?

2022.2.2

### What was the last working version of Home Assistant Core?

2021.12.(last)

### In which browser are you experiencing the issue with?

Firefox 97 & Safari 15.2

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
N/A
```

### Javascript errors shown in your browser console/inspector

```txt
No error in the Browsers Javascript Console
```

### Additional information

I see the following in my homeassistant.log every time I trye an rename a device:
```
2022-02-05 21:36:56 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139628299530048] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/config/device_registry.py", line 66, in websocket_update_device
    msg["disabled_by"] = DeviceEntryDisabler(msg["disabled_by"])
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: None is not a valid DeviceEntryDisabler
2022-02-05 21:36:56 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/config/device_registry.py", line 66, in websocket_update_device
    msg["disabled_by"] = DeviceEntryDisabler(msg["disabled_by"])
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: None is not a valid DeviceEntryDisabler

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 29, in _handle_async_response
    connection.async_handle_exception(msg, err)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 143, in async_handle_exception
    self.send_message(messages.error_message(msg["id"], code, err_message))
KeyError: 'id'
```

**Comment by prof7bit** [comment]
This also affects the area in the same dialog. When opening it for the very first time (new browser session, closed and reopened app) the buttons appear clickable but neither the name nor the area edits will be applied when clicking "update", the next time you open this dialog it will be populated with old values again.

**Comment by shirou93** [comment]
Have same issue with change area in devices. Refresh page return old values in 2022.2.2

**Comment by Daneish** [comment]
I also had this issue in 2022.2.2. I found if I disabled the device, I could successfully rename it, however I encounter the same issue trying to re-enable it.

**Comment by rb2k** [comment]
Can confirm that I was able to re-enable after downgrading using:

ha core update --version 2022.2.1

(In my case a zwave device, but I guess it doesn't matter too much)
