### ISSUE TITLE
History page loading forever

### ISSUE THREAD

**Issue by SirDester** [home-assistant/frontend#11605]
### The problem

Hello,
after updating to latest version (but I can't be sure the problem existed also before the update) accessing the History page the loading hangs forever. Every access is followed by an error entry in the log file related to "components/system_log/__init__.py:190"

### What version of Home Assistant Core has the issue?

Home Assistant 2022.2.3

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

History

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/history

### Anything in the logs that might be useful for us?

```txt
Home assistant log reports an entry for every access to History page:

2022-02-08 09:56:15 ERROR (MainThread) [frontend.js.latest.202202030] :0:0 ResizeObserver loop completed with undelivered notifications.

The error details are:

Logger: frontend.js.latest.202202030
Source: components/system_log/__init__.py:190

Looking further in browser console there's a javascript error related to "Uncaught (in promise) RangeError: Invalid time value":

9f5922e0.js:1 Uncaught (in promise) RangeError: Invalid time value
at s (9f5922e0.js:1:1159)
at d (9f5922e0.js:1:4723)
at state-history-charts.ts:17:1
at state-history-charts.ts:17:1
at Array.forEach (<anonymous>)
at h (state-history-charts.ts:17:1)
at r.value (ha-panel-history.ts:115:1)
```

### Additional information

After trying reboot, browser cache clearing and another fresh browser (Chrome) i decided to try to purge all the events from the database (Developer tools -> Services -> recorder.purge with keep_days: 0) and the problem disappeared.

What would be nice is if an invalid date/time is found in the recorded event in database, the History _init_ should not hang but report that error (end eventually the entity with malformed date/time) to the error log so you can purge the single entity instead of loose the entire history of Home Assistant to solve the problem.

Thanks in advance.

**Comment by SirDester** [comment]
@bramkragten
Thanks for moving the issue to the right place, sorry I opened it wrongly :)

**Comment by rcblackwell** [comment]
I'm seeing the same behavior as SirDister. Began after updating to HA 2022.2.3. Chrome shows the following error;

```
9f5922e0.js:1 Uncaught (in promise) RangeError: Invalid time value
at s (9f5922e0.js:1:1159)
at d (9f5922e0.js:1:4723)
at state-history-charts.ts:17:1
at state-history-charts.ts:17:1
at Array.forEach (<anonymous>)
at h (state-history-charts.ts:17:1)
at r.value (ha-panel-history.ts:115:1)
```

**Comment by Stevenchi36** [comment]
Also getting this behavior after updating to 2022.2.5 (Might have been happening prior to this, but I haven't noticed it until now)

Getting this error message on Firefox 97.0:
`Uncaught (in promise) RangeError: date value is not finite in DateTimeFormat.format()`

**Comment by lintaba** [comment]
Same issue. (originally thought its https://github.com/home-assistant/frontend/issues/10515, might be related..)

This action had been disabled, that may caused this problem.
Relevant json response:
```json
[{
		"entity_id": "button.shelly_ota_update",
		"state": "unknown",
		"attributes": {
			"device_class": "update",
			"friendly_name": "shelly OTA Update"
		},
		"last_changed": "2022-02-11T18:00:00+00:00",
		"last_updated": "2022-02-11T18:00:00+00:00"
	}, {
		"state": "unavailable",
		"last_changed": "2022-02-11T18:02:51.489805+00:00"
	}, {
		"state": "unknown",
		"last_changed": "2022-02-11T18:02:51.867532+00:00"
	}, {
		"entity_id": "button.shelly_ota_update",
		"state": "",
		"attributes": {},
		"last_changed": "2022-02-11T18:03:02.567939+00:00",
		"last_updated": "2022-02-11T18:03:02.567939+00:00"
	}],
```
I think the `state=""` is the problem here.

same stacktrace, here is what `at d (9f5922e0.js:1:4723)` is actually:
https://github.com/home-assistant/frontend/blob/dev/src/common/entity/compute_state_display.ts#L126

the issue is that it checks for unknowns and unavialables at https://github.com/home-assistant/frontend/blob/dev/src/common/entity/compute_state_display.ts#L19, but does not checks for empty value. (haven't done a root analysis about why/how can it be empty, maybe in a followup?)

anyways, i made a PR, that may fix it :)

**Comment by lintaba** [comment]
hotfix:
 - CREATE A FULL BACKUP
 - install addons/sqlite web on HA, and open its web UI
 - in states, run `DELETE FROM "states" where state is null`

it will remove all records from db without state. may delete more stuff thats needed, but at least you won't need to loose all your history.

**Comment by rcblackwell** [comment]
@lintaba , followed the provided instruction.  History loads okay now. Doesn't seem like many records were lost. The crucial ones were retained!

**Comment by SirDester** [comment]
@lintaba, Thanks for the hotfix and the PR, alas I already cleaned my history at the beginning (but as I told I don't use home assistant from so much time, my history was not so valuable...) so I can't directly check but analysis is good.

**Comment by Eckart0** [comment]
@lintaba 

My futile attempt to fix the poblem was to use MariaDB and phpMyAdmin on an separate Server for DB administration. 

Now I uses your hotfix "[DELETE] FROM states WHERE state is null".
It  has cleaned 347 records - but i see no effect: History still does not load.

Is there any ohter idea? Do I have to delect local files?

Regards, Eckart

**Comment by lintaba** [comment]
You may have a different kind of invalid date. Deleting the db will resolve the issue, but you'll loose your history.
There is an ongoing patch (see relevant pr's) that will resolve the issue sooner or later.

If you have the time (and since you are messing around with hass, probably have :D ), you can figure out exactly what date is bad. (For me it was empty date, but you can have a non-empty invalid value too.)
- Use chrome debugger
- stop on exception
- go up to previous call
- check local variables:
   - what is the invalid value?
   - which record causes it?
- you can cross reference it with the json data response, or with your database, to see what do delete.

**Comment by lintaba** [comment]
@Eckart0 please keep your pastes a bit shorter, you are killing my inbox :D 

The issue comes from two factors: 1) bad data + 2) bad error handling.

fix for 2 is wip and waiting to be released, currently on dev branch.
You can do a ~hotfix on your db, without any warranty/promise that it will work..
