### ISSUE TITLE
Unkown error while browsing through Media using Volumio

### ISSUE THREAD

**Issue by azrael783** [home-assistant/frontend#12276]
### The problem

I use the Volumio integration to play musik. When I try to browse through "Media" I always get an "unkown error". This is the error message in the log:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/volumio/browse_media.py:146
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14:22:25 (7 occurrences)
Last logged: 14:22:56

[2783808312] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1179, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/usr/src/homeassistant/homeassistant/components/volumio/media_player.py", line 289, in async_browse_media
    return await browse_node(
  File "/usr/src/homeassistant/homeassistant/components/volumio/browse_media.py", line 146, in browse_node
    json_item = json.loads(media_content_id)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 75 (char 74)
```
Volumio is runnung on a Pi0 2. The version of Volumio is 3.198. The media player is working fine so far. Browsing through "Media" using the Spotify integration works also fine.

### What version of Home Assistant Core has the issue?

core-2022.2.5

### What was the last working version of Home Assistant Core?

unknown

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

Volumio

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/volumio/

**Comment by olympia** [comment]
Thank you @balloob for the very quick feedback. Do you have someone in mind who would be the best to contact regarding this?

**Comment by olympia** [comment]
@zsarnett Many thanks for the fix!
Do you have a hint on which HA release this will be included?

**Comment by balloob** [comment]
2022.5

**Comment by olympia** [comment]
I confirm that this is working ok now. Thank you very much for the fix!
