### ISSUE TITLE
Devices not shown on device dashboard - Javascript TypeError

### ISSUE THREAD

**Issue by kleinc80** [home-assistant/frontend#12338]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I navigate to the devices dashboard no devices are shown, it simply says "no data". The browser's console logs an error at ha-config-device-page.ts:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at ha-config-device-page.ts:72:1
    at Array.map (<anonymous>)
    ...
```
I obviously do have devices in my installation and I can reach them, if I go via an area or if I click on "devices" on an integration with one device only (as this navigates directly to the device and skips the devices dashboard).

This happens on 2 machines (Windows 10 and 11) with all browsers I tried (Google Chrome, MS Edge) and it even happens in the Home Assistant Companion App (Android). Looks like by backend is returning a None-object in some place it shouldn't do that.

I noticed this issue in core-2022.3.x and core-2022.4.x but unfortunately I cannot tell when this started.

![no-data](https://user-images.githubusercontent.com/59744911/163680129-6a9cf472-2f70-45e6-9ab9-277eb3187b8f.png)

### Describe the behavior you expected

To see the list of devices. :-)

### Steps to reproduce the issue

I tried 2 way of navigating to "devices":
1. directly via <<my_ha_url>>/config/devices/dashboard
2. on the integrations dashboard by clicking on "devices" for an integration with more than 1 device

### What version of Home Assistant Core has the issue?

core-2022.4.4

### In which browser are you experiencing the issue with?

Google Chrome 100.0.4896.88 (64-Bit)

### Which operating system are you using to run this browser?

Windows 11

### Javascript errors shown in your browser console/inspector

```txt
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at ha-config-device-page.ts:72:1
    at Array.map (<anonymous>)
    at F.<anonymous> (ha-config-device-page.ts:72:1)
    at F._devicesAndFilterDomains (typography.js:181:1)
    at F.value (ha-config-devices-dashboard.ts:343:1)
    at F.update (styles.ts:368:1)
    at F.performUpdate (styles.ts:368:1)
    at F.scheduleUpdate (styles.ts:368:1)
    at F._$EC (styles.ts:368:1)
```

**Comment by spacegaier** [comment]
Yes, that is what was weird for me as well from the callstack. I was just hoping that the code navigation might end up somewhere else that provides more insight 😆.

`_devicesAndFilterDomains` helps a bit (although then the corresponding file in the callstack makes no sense). There could potentially be an area without a name (line 200 of `ha-config-devices-dashboard`) which might cause the error. But that is now just guessing in the dark unfortunately...

**Comment by kleinc80** [comment]
You mean/guess, areaLookup[device.area_id] is None? That would mean I have a device with area_id, but the area_id does not exist in my areas. I'll check device_registry and area_registry for such cases and let you know!

**Comment by kleinc80** [comment]
Hi Philip (@spacegaier),

You're great! :-)
I had 5 devices with an `area_id` which did not exist (or not exist anymore?). Consequently `areaLookup[device.area_id]` returned `None` and areaLookup[device.area_id].name threw the error (line 200 of `ha-config-devices-dashboard`).

I have no idea how that happened and when, unfortunately. We could make the code a but more robust to prevent this in future:

`area: device.area_id ? areaLookup[device.area_id].name : "—"`
->
`area: device.area_id && areaLookup[device.area_id] ? areaLookup[device.area_id].name : "—"`

However, that's actually fixing a problem which should never occur in first place.
