### ISSUE TITLE
Error adding integrations since 2022.4.x with Chrome 100

### ISSUE THREAD

**Issue by JohnONolan** [home-assistant/frontend#12517]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Very similar to #11563 

Clicking "add integration" or "configure" on the integrations page produces frontend errors in latest Chrome. Have cleared all cache/application data, restarted browser, restarted HA, etc. Issue is not present when using Safari.

Log:

```
Logger: frontend.js.latest.202204050
Source: components/system_log/__init__.py:190
First occurred: 11:31:32 AM (1 occurrences)
Last logged: 11:31:32 AM

http://192.168.13.250:8123/frontend_latest/48944a97.js:477:36 Uncaught SyntaxError: Unexpected string
```

Screenshot:

![CleanShot 2022-04-29 at 12 05 38@2x](https://user-images.githubusercontent.com/120485/165982166-cbb6c087-844d-4059-a146-d882090bdb52.png)

### Describe the behavior you expected

Normal loading of the modal UI for adding or configuring an integration

### Steps to reproduce the issue

Click "add integration" or "configure" on any existing integration.

### What version of Home Assistant Core has the issue?

core-2022.4.7

### In which browser are you experiencing the issue with?

Google Chrome 100.0.4896.127 (Official Build) (arm64)

### Which operating system are you using to run this browser?

macOS Monterey 12.3.1

### Javascript errors shown in your browser console/inspector

```txt
Uncaught SyntaxError: Unexpected string (at 48944a97.js:477:36)
2styles.ts:368 Uncaught (in promise) ChunkLoadError: Loading chunk 9647 failed.
(missing: http://192.168.13.250:8123/frontend_latest/48944a97.js)
    at Object.u.f.j (styles.ts:368:1)
    at styles.ts:368:1
    at Array.reduce (<anonymous>)
    at Function.u.e (styles.ts:368:1)
    at n (show-dialog-config-flow.ts:200:1)
    at o (ha-svg-icon.ts:5:1)
    at s.<anonymous> (ha-svg-icon.ts:5:1)
    at i (typography.js:181:1)
    at o (show-dialog-config-flow.ts:200:1)
    at a (ha-checkbox.ts:7:1)
```
```


### Additional information

_No response_

**Comment by JohnONolan** [comment]
This was a local networking issue with my router - reconfiguring the wifi access point stopped the packet loss which was causing this problem
