### ISSUE TITLE
BMW Connected Integration says : local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by pjannink** [home-assistant/frontend#12814]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The BMW Connected integration stopped working recently, mat be after upgrading to 2022.5.5

### Describe the behavior you expected

Integration should work :-)

### Steps to reproduce the issue

1. No steps needed. Integration does not start anymore
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.5.5

### What was the last working version of Home Assistant Core?

2022.5.4

### In which browser are you experiencing the issue with?

Firefox 100.0.2

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
All states are Unavailable.
```

### Problem-relevant frontend configuration

```yaml
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: sensor.apk_expiration_2 <from other integration
    title: CAR NAME
  - type: entities
    entities:
      - entity: sensor.apk_expiration <from other integration
      - entity: device_tracker.x1_xdrive20i
      - entity: binary_sensor.x1_xdrive20i_check_control_messages
      - entity: binary_sensor.x1_xdrive20i_condition_based_services
      - entity: lock.x1_xdrive20i_lock
      - entity: binary_sensor.x1_xdrive20i_door_lock_state
      - entity: binary_sensor.x1_xdrive20i_windows
      - entity: binary_sensor.x1_xdrive20i_lids
      - entity: sensor.x1_xdrive20i_remaining_fuel
      - entity: sensor.x1_xdrive20i_remaining_range_total
      - entity: sensor.x1_xdrive20i_mileage
    title: BMW CAR NAME
    show_header_toggle: false
```

### Javascript errors shown in your browser console/inspector

```txt
Logger: homeassistant.components.bmw_connected_drive.coordinator
Source: components/bmw_connected_drive/coordinator.py:59
Integration: BMW Connected Drive (documentation, issues)
First occurred: May 27, 2022, 19:24:44 (665 occurrences)
Last logged: 10:10:14

Unexpected error fetching bmw_connected_drive-paul.jannink@gmail.com data: local variable 'response' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 128, in _login_row_na
    r_oauth_settings.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://cocoapi.bmwgroup.com/eadrax-ucs/v1/presentation/oauth/config

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 220, in _login_row_na
    err = response.json()
UnboundLocalError: local variable 'response' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/coordinator.py", line 59, in _async_update_data
    self.account = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 88, in __init__
    self._get_vehicles()
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 383, in _get_vehicles
    self._get_oauth_token()
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 113, in _get_oauth_token
    raise ex
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 99, in _get_oauth_token
    token_data = self._login_row_na()
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 223, in _login_row_na
    _LOGGER.error("Authentication failed: %s", response.text)
UnboundLocalError: local variable 'response' referenced before assignment
```

**Comment by philmale** [comment]
Same here integration reporting on the integrations page: Retrying setup: local variable 'response' referenced before assignment

HA: core-2022.5.5

Worked under HA 2022.5.4

```
Logger: bimmer_connected.account
Source: /usr/local/lib/python3.9/site-packages/bimmer_connected/account.py:112 
First occurred: 28 May 2022, 23:25:11 (45 occurrences) 
Last logged: 00:15:22

local variable 'response' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 128, in _login_row_na
    r_oauth_settings.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://cocoapi.bmwgroup.com/eadrax-ucs/v1/presentation/oauth/config

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 220, in _login_row_na
    err = response.json()
UnboundLocalError: local variable 'response' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 99, in _get_oauth_token
    token_data = self._login_row_na()
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 223, in _login_row_na
    _LOGGER.error("Authentication failed: %s", response.text)
UnboundLocalError: local variable 'response' referenced before assignment
```

**Comment by danfulton72** [comment]
Same here, reverted to 2022.5.4, that is also now not working.

**Comment by Taygeto** [comment]
Same issue here. Tried removing & re-adding the integration, but now it just says an "Unknown error occurred" after I enter my BMW credentials and try to log on.
At the same time, I see that the status in the "My BMW" app also has been suffering from some delayed data refresh in the past few days, so perhaps something on the BWM side?

**Comment by danfulton72** [comment]
I'm guessing it's related to this issue 

https://github.com/bimmerconnected/bimmer_connected/issues/444

Will have a play later and see.
