### ISSUE TITLE
Missing source entity selector in Switch-as-X helper UI

### ISSUE THREAD

**Issue by Bodge-IT** [home-assistant/frontend#13287]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![image](https://user-images.githubusercontent.com/1881642/181251293-4a7f457c-0a0d-4859-af18-18c3c9b31dae.png)

Source entity selector missing

### Describe the behavior you expected

I need an entity to switch from

### Steps to reproduce the issue

1. Goto to switch as x helper, try to create 
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.6 +

### What was the last working version of Home Assistant Core?

2022-05-*

### In which browser are you experiencing the issue with?

Chrome, Brave, FF, Opera

### Which operating system are you using to run this browser?

Win7

### Javascript errors shown in your browser console/inspector

```txt
In Chrome:
dialog-helper-detail.ts:48 Uncaught TypeError: Cannot read properties of undefined (reading 'dialogClosedCallback')
    at F.value (dialog-helper-detail.ts:48:1)
    at F.handleEvent (styles.ts:369:1)
    at a.fireRequestSelected (mwc-list-item-base.ts:224:1)
    at a.<anonymous> (mwc-list-item-base.ts:224:1)
    at d79e126a.js:2:2776
    at Map.forEach (<anonymous>)
    at e.updated (d79e126a.js:2:2702)
    at a._$AE (styles.ts:369:1)
    at a.performUpdate (styles.ts:369:1)
    at a.scheduleUpdate (styles.ts:369:1)
value @ dialog-helper-detail.ts:48
handleEvent @ styles.ts:369
fireRequestSelected @ mwc-list-item-base.ts:224
(anonymous) @ mwc-list-item-base.ts:224
(anonymous) @ d79e126a.js:2
e.updated @ d79e126a.js:2
_$AE @ styles.ts:369
performUpdate @ styles.ts:369
scheduleUpdate @ styles.ts:369
_$EC @ styles.ts:369
await in _$EC (async)
requestUpdate @ styles.ts:369
set @ styles.ts:369
setSelectedStateForElementIndex @ mwc-list-base.ts:270
setSingleSelectionAtIndex_ @ 5d3d20ff.js:2
setSelectedIndexOnAction_ @ 5d3d20ff.js:2
handleSingleSelection @ 5d3d20ff.js:2
onRequestSelected @ mwc-list-base.ts:270
handleEvent @ styles.ts:369
fireRequestSelected @ mwc-list-item-base.ts:224
onClick @ mwc-list-item-base.ts:224
cb @ mwc-circular-progress-base.ts:156
af2956b0.js:1 Uncaught (in promise) TypeError: e.toLowerCase is not a function
    at n (af2956b0.js:1:1090)
    at ha-entity-picker.ts:32:1
    at Array.sort (<anonymous>)
    at F.<anonymous> (ha-entity-picker.ts:32:1)
    at F._getStates (typography.js:181:1)
    at F.value (ha-entity-picker.ts:32:1)
    at F.performUpdate (styles.ts:369:1)
    at F.scheduleUpdate (styles.ts:369:1)
    at F._$EC (styles.ts:369:1)

Also these:
Failed to load resource: the server responded with a status of 404 (Not Found)
:8123/hacsfiles/elements/simple-clock-card/simple-clock-card.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
:8123/hacsfiles/lovelace-swipe-navigation/swipe-navigation.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
1000browser_mod.js:145 Uncaught (in promise) 3
```

**Comment by Quentame** [comment]
On the "What version of Home Assistant Core has the issue?" section, we are waiting for a value like "2022.8.0"

**Comment by Bodge-IT** [comment]
@Quenteme, this was already in the details.  It was there from 2022-05.  It has now been fixed.  Not sure when.
