### ISSUE TITLE
Hue Lights Prolem that has something to do with Hue HDMI Sync. 

### ISSUE THREAD

**Issue by jimmyhawkin** [home-assistant/frontend#13397]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When i launch light i sometimes get problems that gives an error saying it is have problems communicating with the light.
But i can controll it and i can change lights to colors i want to have etc. 

**From what i can see is that it has something to do with the Hue lights that are part of Philips Hue HDMI Sync group in my livingroom.** 
When i try to Change the lights on them the error comes. 

feels like i would need to do some kind of exeption setting to them. 

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hue/bridge.py:134
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:45:03 (6 occurrences)
Last logged: 16:45:16

[139992774346544] Request failed due connection error: 400, message='Bad Request', url=URL('https://10.100.3.253/clip/v2/resource/light/123168d4-1432-43bd-aa04-15e586301146')
[139992774346544] Request failed due connection error: 400, message='Bad Request', url=URL('https://10.100.3.253/clip/v2/resource/light/7c695f43-9500-4c54-bd3b-000c444455fc')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hue/bridge.py", line 123, in async_request_call
    return await task(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohue/v2/controllers/lights.py", line 103, in set_state
    await self.update(id, update_obj)
  File "/usr/local/lib/python3.10/site-packages/aiohue/v2/controllers/base.py", line 159, in update
    await self._bridge.request("put", endpoint, json=data)
  File "/usr/local/lib/python3.10/site-packages/aiohue/v2/__init__.py", line 176, in request
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://10.100.3.253/clip/v2/resource/light/123168d4-1432-43bd-aa04-15e586301146')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 553, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/components/group/light.py", line 191, in async_turn_on
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 553, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/components/hue/v2/light.py", line 211, in async_turn_on
    await self.bridge.async_request_call(
  File "/usr/src/homeassistant/homeassistant/components/hue/bridge.py", line 134, in async_request_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Request failed due connection error: 400, message='Bad Request', url=URL('https://10.100.3.253/clip/v2/resource/light/123168d4-1432-43bd-aa04-15e586301146')
```

### Describe the behavior you expected

No errors, Work fine untill latest patch. 

### Steps to reproduce the issue

1. Open light with more info

### What version of Home Assistant Core has the issue?

Latest

### What was the last working version of Home Assistant Core?

I think it worked fine 1-2 core patches ago

### In which browser are you experiencing the issue with?

Chrome, Safari

### Which operating system are you using to run this browser?

Iphone,  Windows

### State of relevant entities

```txt
All enteties are online and work to controll. But i see some wierd ui changes after the first error happens.
```

### Problem-relevant frontend configuration

```yaml
- deep_press: true
                entity: light.vardagsrum_golvlampor
                icon: hue:floor-shade
                name: Golvlampor
                tap_action:
                  action: toggle
                  entity: light.vardagsrum_golvlampor
                  haptic: light
                hold_action:
                  haptic: heavy
                  action: popup
                offStates:
                  - 'off'
                  - unavailable
                  - otillgänglig
                  - unknown
                popupExtend:
                  actions:
                    - color: '#d8d9e1'
                      service: light.turn_on
                      service_data:
                        color_temp: 153
                        entity_id: light.vardagsrum_golvlampor
                    - color: '#d5b08d'
                      service: light.turn_on
                      service_data:
                        color_temp: 326
                        entity_id: light.vardagsrum_golvlampor
                    - color: '#ce944b'
                      service: light.turn_on
                      service_data:
                        color_temp: 500
                        entity_id: light.vardagsrum_golvlampor
                    - color: '#271a00'
                      service: light.turn_on
                      service_data:
                        brightness: 5
                        color_temp: 500
                        entity_id: light.vardagsrum_golvlampor
                    - color: '#2E8B57'
                      service: light.turn_on
                      service_data:
                        color_name: seagreen
                        entity_id: light.vardagsrum_golvlampor
                    - color: '#D2691E'
                      service: light.turn_on
                      service_data:
                        color_name: chocolate
                        entity_id: light.vardagsrum_golvlampor
                    - color: '#FF00FF'
                      service: light.turn_on
                      service_data:
                        color_name: fuchsia
                        entity_id: light.vardagsrum_golvlampor
                    - color: '#DC143C'
                      service: light.turn_on
                      service_data:
                        color_name: crimson
                        entity_id: light.vardagsrum_golvlampor
                    - color: '#1E90FF'
                      service: light.turn_on
                      service_data:
                        color_name: dodgerblue
                        entity_id: light.vardagsrum_golvlampor
                    - color: '#FFD700'
                      service: light.turn_on
                      service_data:
                        color_name: gold
                        entity_id: light.vardagsrum_golvlampor
                  actionsInARow: 5
                  displayType: slider
                  settings:
                    closeButton: stäng
                    openButton: Inställningar
                  settingsCard:
                    cardOptions:
                      brightness: true
                      child_card: true
                      persist_features: true
                      consolidate_entities: true
                      hide_header: false
                      shorten_cards: false
                      entity: light.vardagsrum_golvlampor
                      secondary_info: last-changed
                      smooth_color_wheel: true
                    cardStyle: |
                      background-color:#FFF;
                    type: custom:light-entity-card
```

### Additional information

Its not a Proxy problem, I checked the settings between the light that has problem and the group light with all lights that the error does not happen on.

**Comment by Quentame** [comment]
Hi !
This isn't a frontend issue, create one on the core repo and close this one.
Thanks 😊

**Comment by jimmyhawkin** [comment]
Oh im soz. i remade it in core insted.
