### ISSUE TITLE
Configuration panel unaccessible with error in console

### ISSUE THREAD

**Issue by Treyone** [home-assistant/frontend#13746]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The configuration panel at `/config/system` is is inaccessible and displays a blank page. The browser console displays a frontend code error:

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/3852427/190132883-3976629d-adfe-4e3b-aeae-bf6d47c3366e.png">

I tried with several browsers, clear cache, etc. I can't restore a snapshot (it's in the config panel) and I can't restore using SSH neither:

```sh
ha backups restore e02b85fc
Processing... Done.

Error: Unknown error, see supervisor
```
But... supervisor is under configuration panel.

### Describe the behavior you expected

I expected configuration panel to show up as usual :)

### Steps to reproduce the issue

1. Open HA main page
2. Click "Settings"  > " Configuration" (I hope that's the right translation, I don't use HA in english... and that's maybe where the issue comes from, seeing the exception message)

### What version of Home Assistant Core has the issue?

9.3

### What was the last working version of Home Assistant Core?

9.2

### In which browser are you experiencing the issue with?

Chrome 88

### Which operating system are you using to run this browser?

MacOS Big Sur

### Problem-relevant frontend configuration

```yaml
Language: French
```

### Javascript errors shown in your browser console/inspector

```txt
typography.js:181 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'language')
    at i (typography.js:181:1)
    at r.value (ha-card.ts:5:1)
    at r.performUpdate (styles.ts:370:1)
    at r.scheduleUpdate (styles.ts:370:1)
    at r._$EC (styles.ts:370:1)
i @ typography.js:181
value @ ha-card.ts:5
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
o @ styles.ts:370
b @ styles.ts:370
w @ styles.ts:370
r @ ha-card.ts:5
E @ typography.js:181
t @ typography.js:181
p @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
S @ styles.ts:370
update @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
o @ styles.ts:370
b @ styles.ts:370
w @ styles.ts:370
r @ ha-list-item.ts:7
E @ typography.js:181
t @ typography.js:181
window.CustomElementRegistry.define @ typography.js:181
finisher @ styles.ts:370
runClassFinishers @ ha-list-item.ts:7
(anonymous) @ ha-list-item.ts:7
(anonymous) @ ha-list-item.ts:7
u.a @ styles.ts:370
99417 @ ha-list-item.ts:7
u @ styles.ts:370
Promise.then (async)
load @ 312c80d9.js:1
value @ hass-loading-screen.ts:11
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
o @ styles.ts:370
b @ styles.ts:370
r @ hass-loading-screen.ts:11
s @ 312c80d9.js:1
E @ typography.js:181
t @ typography.js:181
value @ hass-loading-screen.ts:11
value @ hass-loading-screen.ts:11
_currentLoadProm.l.then._currentLoadProm @ hass-loading-screen.ts:11
Promise.then (async)
value @ hass-loading-screen.ts:11
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
set @ styles.ts:370
k @ styles.ts:370
_$AI @ styles.ts:370
m @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
S @ styles.ts:370
update @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
set @ styles.ts:370
k @ styles.ts:370
_$AI @ styles.ts:370
m @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
S @ styles.ts:370
update @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
set @ styles.ts:370
value @ styles.ts:370
(anonymous) @ styles.ts:370
s @ core.79519174.js:1
(anonymous) @ core.79519174.js:1
Promise.then (async)
d @ core.79519174.js:1
u @ core.79519174.js:1
(anonymous) @ core.79519174.js:1
subscribe @ core.79519174.js:1
(anonymous) @ core.79519174.js:1
(anonymous) @ core.79519174.js:1
Promise.then (async)
(anonymous) @ core.79519174.js:1
(anonymous) @ core.79519174.js:1
(anonymous) @ core.79519174.js:1


system:1 Uncaught (in promise) {message: 'A listener indicated an asynchronous response by r…age channel closed before a response was received'}
```

**Comment by ludeeus** [comment]
Update to 2022.9.4

**Comment by erkr** [comment]
Let's forget 9.3 😼

**Comment by Treyone** [comment]
Indeed, way better with 9.4, I just didn't get the update notification yet.
Thanks for your reactivity :+1:
