### ISSUE TITLE
Error setting up entry XXXXX for august

### ISSUE THREAD

**Issue by razim7** [home-assistant/frontend#13890]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

August lock not available anymore

### Describe the behavior you expected

Tried to delete and re-configure the august integration without luck, locks are not available anymore.

### Steps to reproduce the issue

1. have august integration

### What version of Home Assistant Core has the issue?

Home Assistant 2022.9.7

### What was the last working version of Home Assistant Core?

Frontend 20220907.2 - latest

### In which browser are you experiencing the issue with?

Version 105.0.5195.125 (Official Build) (arm64)

### Which operating system are you using to run this browser?

12.6 (21G115)

### State of relevant entities

```txt
Unavailable
```

### Problem-relevant frontend configuration

```yaml
integration: august
```

### Javascript errors shown in your browser console/inspector

```txt
Logger: homeassistant.config_entries
Source: components/august/activity.py:137
First occurred: 17:22:43 (1 occurrences)
Last logged: 17:22:43

Error setting up entry XXXXX for august
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/august/__init__.py", line 50, in async_setup_entry
    return await async_setup_august(hass, entry, august_gateway)
  File "/usr/src/homeassistant/homeassistant/components/august/__init__.py", line 90, in async_setup_august
    await data.async_setup()
  File "/usr/src/homeassistant/homeassistant/components/august/__init__.py", line 180, in async_setup
    await self.activity_stream.async_setup()
  File "/usr/src/homeassistant/homeassistant/components/august/activity.py", line 42, in async_setup
    await self._async_refresh(utcnow())
  File "/usr/src/homeassistant/homeassistant/components/august/activity.py", line 96, in _async_refresh
    await self._async_update_device_activities(time)
  File "/usr/src/homeassistant/homeassistant/components/august/activity.py", line 100, in _async_update_device_activities
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 82, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/components/august/activity.py", line 49, in _async_update_house_id
    await self._async_update_house_id(house_id)
  File "/usr/src/homeassistant/homeassistant/components/august/activity.py", line 137, in _async_update_house_id
    activities = await self._api.async_get_house_activities(
  File "/usr/local/lib/python3.10/site-packages/yalexs/api_async.py", line 102, in async_get_house_activities
    return _process_activity_json(await response.json())
  File "/usr/local/lib/python3.10/site-packages/yalexs/api_common.py", line 158, in _process_activity_json
    activity = _activity_from_dict(SOURCE_LOG, activity_json)
  File "/usr/local/lib/python3.10/site-packages/yalexs/api_common.py", line 122, in _activity_from_dict
    return DoorbellDingActivity(source, activity_dict)
  File "/usr/local/lib/python3.10/site-packages/yalexs/activity.py", line 219, in __init__
    self._activity_start_time = epoch_to_datetime(info.get("started"))
  File "/usr/local/lib/python3.10/site-packages/yalexs/activity.py", line 97, in epoch_to_datetime
    return datetime.fromtimestamp(int(epoch) / 1000.0)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by razim7** [comment]
I saw you're active with August issues, any chance you can advise? @bdraco

**Comment by bdraco** [comment]
August recently changed all the activity responses in the api so we have been having to adjust as reports come in.

Can you enable debug logs for `yalexs`, restart and email me all the activities?

nick@koston.org


Thanks
