### ISSUE TITLE
Some cards doesn't load sometimes after 2023.1

### ISSUE THREAD

**Issue by felipecrs** [home-assistant/frontend#15048]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

For some reason several buttons didn't load. This issue happens sometimes, but not all the time. I think I caught it 4 times before this report.

![20230109_010430](https://user-images.githubusercontent.com/29582865/211239429-6f416b49-b919-45ce-8f67-aea826fdd97d.jpg)

### Describe the behavior you expected

Not to fail to load some buttons.

### Steps to reproduce the issue

Unfortunately I don't know. However, I have an environment in which I can trigger the issue.

### What version of Home Assistant Core has the issue?

2023.1.1

### What was the last working version of Home Assistant Core?

2022.12 (latest patch release)

### In which browser are you experiencing the issue with?

Fully Kiosk Browser, Chrome Webview 108

### Which operating system are you using to run this browser?

Android 10

### Javascript errors shown in your browser console/inspector

```txt
Some resource load requests were throttled while the tab was in background, and no request was sent from the queue in the last 1 minute. This means previously requested in-flight requests haven't received any response from servers. See https://www.chromestatus.com/feature/5527160148197376 for more details
card-mod.js:5 CARD-MOD 3.2.0 IS INSTALLED
0c592bda.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'cover.portao_do_terreiro')
    at m (0c592bda.js:1:5577)
    at h (0c592bda.js:1:3731)
    at C.value (d414e23c.js:219:24)
    at C.update (app.c7254a29.js:1366:31695)
    at C.performUpdate (app.c7254a29.js:1366:30550)
    at C.scheduleUpdate (app.c7254a29.js:1366:30197)
    at C._$EC (app.c7254a29.js:1366:30105)
0c592bda.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'light.luz_da_estrada')
    at m (0c592bda.js:1:5577)
    at h (0c592bda.js:1:3731)
    at C.value (d414e23c.js:219:24)
    at C.update (app.c7254a29.js:1366:31695)
    at C.performUpdate (app.c7254a29.js:1366:30550)
    at C.scheduleUpdate (app.c7254a29.js:1366:30197)
    at C._$EC (app.c7254a29.js:1366:30105)
0c592bda.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'cover.portao_da_garagem_de_baixo')
    at m (0c592bda.js:1:5577)
    at h (0c592bda.js:1:3731)
    at C.value (d414e23c.js:219:24)
    at C.update (app.c7254a29.js:1366:31695)
    at C.performUpdate (app.c7254a29.js:1366:30550)
    at C.scheduleUpdate (app.c7254a29.js:1366:30197)
    at C._$EC (app.c7254a29.js:1366:30105)
0c592bda.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'cover.portao_da_garagem_de_cima')
    at m (0c592bda.js:1:5577)
    at h (0c592bda.js:1:3731)
    at C.value (d414e23c.js:219:24)
    at C.update (app.c7254a29.js:1366:31695)
    at C.performUpdate (app.c7254a29.js:1366:30550)
    at C.scheduleUpdate (app.c7254a29.js:1366:30197)
    at C._$EC (app.c7254a29.js:1366:30105)
0c592bda.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'light.luzes_do_terreiro')
    at m (0c592bda.js:1:5577)
    at h (0c592bda.js:1:3731)
    at C.value (d414e23c.js:219:24)
    at C.update (app.c7254a29.js:1366:31695)
    at C.performUpdate (app.c7254a29.js:1366:30550)
    at C.scheduleUpdate (app.c7254a29.js:1366:30197)
    at C._$EC (app.c7254a29.js:1366:30105)
0c592bda.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'light.luz_do_poste')
    at m (0c592bda.js:1:5577)
    at h (0c592bda.js:1:3731)
    at C.value (d414e23c.js:219:24)
    at C.update (app.c7254a29.js:1366:31695)
    at C.performUpdate (app.c7254a29.js:1366:30550)
    at C.scheduleUpdate (app.c7254a29.js:1366:30197)
    at C._$EC (app.c7254a29.js:1366:30105)
0c592bda.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'light.luzes_dos_fundos')
    at m (0c592bda.js:1:5577)
    at h (0c592bda.js:1:3731)
    at C.value (d414e23c.js:219:24)
    at C.update (app.c7254a29.js:1366:31695)
    at C.performUpdate (app.c7254a29.js:1366:30550)
    at C.scheduleUpdate (app.c7254a29.js:1366:30197)
    at C._$EC (app.c7254a29.js:1366:30105)
0c592bda.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'light.luz_colorida')
    at m (0c592bda.js:1:5577)
    at h (0c592bda.js:1:3731)
    at C.value (d414e23c.js:219:24)
    at C.update (app.c7254a29.js:1366:31695)
    at C.performUpdate (app.c7254a29.js:1366:30550)
    at C.scheduleUpdate (app.c7254a29.js:1366:30197)
    at C._$EC (app.c7254a29.js:1366:30105)
0c592bda.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'light.luz_do_porao')
    at m (0c592bda.js:1:5577)
    at h (0c592bda.js:1:3731)
    at C.value (d414e23c.js:219:24)
    at C.update (app.c7254a29.js:1366:31695)
    at C.performUpdate (app.c7254a29.js:1366:30550)
    at C.scheduleUpdate (app.c7254a29.js:1366:30197)
    at C._$EC (app.c7254a29.js:1366:30105)
0c592bda.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'light.arvore_de_natal')
    at m (0c592bda.js:1:5577)
    at h (0c592bda.js:1:3731)
    at C.value (d414e23c.js:219:24)
    at C.update (app.c7254a29.js:1366:31695)
    at C.performUpdate (app.c7254a29.js:1366:30550)
    at C.scheduleUpdate (app.c7254a29.js:1366:30197)
    at C._$EC (app.c7254a29.js:1366:30105)
0c592bda.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'cover.portao_da_rua')
    at m (0c592bda.js:1:5577)
    at h (0c592bda.js:1:3731)
    at C.value (d414e23c.js:219:24)
    at C.update (app.c7254a29.js:1366:31695)
    at C.performUpdate (app.c7254a29.js:1366:30550)
    at C.scheduleUpdate (app.c7254a29.js:1366:30197)
    at C._$EC (app.c7254a29.js:1366:30105)
0c592bda.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'cover.portaozinho_da_rua')
    at m (0c592bda.js:1:5577)
    at h (0c592bda.js:1:3731)
    at C.value (d414e23c.js:219:24)
    at C.update (app.c7254a29.js:1366:31695)
    at C.performUpdate (app.c7254a29.js:1366:30550)
    at C.scheduleUpdate (app.c7254a29.js:1366:30197)
    at C._$EC (app.c7254a29.js:1366:30105)
state-switch.js?hacstag=158756598195:139 STATE-SWITCH 1.9.5 IS INSTALLED 
auto-entities.js?hacstag=1677445841110:172 AUTO-ENTITIES 1.12.1 IS INSTALLED
```

### Additional information

My photo displays an state without internet connection, but this has no relationship with the issue.

**Comment by felipecrs** [comment]
I'm not experiencing this anymore. Yay!
