### ISSUE TITLE
Selecting entities in the configuration of the energy dashboard is not possible

### ISSUE THREAD

**Issue by tripplet** [home-assistant/frontend#15360]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

It is not possible to select entities in the energy dashboard configuration.

### Describe the behavior you expected

Selecting entities in the energy dashboard is possible.

### Steps to reproduce the issue

Open energy dashboard configuration and e.g. try to add a solar system.

### What version of Home Assistant Core has the issue?

2023.2.2

### What was the last working version of Home Assistant Core?

2023.1.7

### In which browser are you experiencing the issue with?

Chrome 109, Firefox 109, Safari 16.3

### Which operating system are you using to run this browser?

macOS Ventura 13.2, Windows 10 22H2

### Javascript errors shown in your browser console/inspector

```txt
ha-statistic-picker.ts:255 Uncaught (in promise) {code: 'unknown_error', message: 'Unknown error'}code: "unknown_error"message: "Unknown error"[[Prototype]]: Object
value @ ha-statistic-picker.ts:255
await in value (async)
value @ ha-statistic-picker.ts:97
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$Ej @ styles.ts:372
await in _$Ej (async)
requestUpdate @ styles.ts:372
u @ styles.ts:372
g @ styles.ts:372
k @ styles.ts:372
F @ 962cf1fa.js:1
E @ typography.js:181
t @ typography.js:181
v @ styles.ts:372
$ @ styles.ts:372
_$AI @ styles.ts:372
j @ styles.ts:372
update @ styles.ts:372
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$Ej @ styles.ts:372
await in _$Ej (async)
requestUpdate @ styles.ts:372
u @ styles.ts:372
g @ styles.ts:372
k @ styles.ts:372
F @ ha-list-item.ts:35
E @ typography.js:181
t @ typography.js:181
(anonymous) @ ha-svg-icon.ts:44
Promise.then (async)
c @ ha-svg-icon.ts:44
(anonymous) @ ha-svg-icon.ts:44
i @ typography.js:181
s @ ha-energy-water-settings.ts:135
value @ ha-energy-solar-settings.ts:148
handleEvent @ styles.ts:372
ha-statistic-picker.ts:255 Uncaught (in promise) {code: 'unknown_error', message: 'Unknown error'}
value @ ha-statistic-picker.ts:255
await in value (async)
value @ ha-statistic-picker.ts:97
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$Ej @ styles.ts:372
await in _$Ej (async)
requestUpdate @ styles.ts:372
u @ styles.ts:372
g @ styles.ts:372
k @ styles.ts:372
F @ 962cf1fa.js:1
E @ typography.js:181
t @ typography.js:181
v @ styles.ts:372
$ @ styles.ts:372
_$AI @ styles.ts:372
j @ styles.ts:372
update @ styles.ts:372
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$Ej @ styles.ts:372
await in _$Ej (async)
requestUpdate @ styles.ts:372
set @ styles.ts:372
value @ ha-list-item.ts:35
c @ ha-svg-icon.ts:44
await in c (async)
(anonymous) @ ha-svg-icon.ts:44
i @ typography.js:181
s @ ha-energy-water-settings.ts:135
value @ ha-energy-solar-settings.ts:148
handleEvent @ styles.ts:372
ha-statistic-picker.ts:255 Uncaught (in promise) {code: 'unknown_error', message: 'Unknown error'}
value @ ha-statistic-picker.ts:255
await in value (async)
value @ ha-statistic-picker.ts:97
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$Ej @ styles.ts:372
await in _$Ej (async)
requestUpdate @ styles.ts:372
u @ styles.ts:372
g @ styles.ts:372
k @ styles.ts:372
F @ 962cf1fa.js:1
E @ typography.js:181
t @ typography.js:181
v @ styles.ts:372
$ @ styles.ts:372
_$AI @ styles.ts:372
j @ styles.ts:372
update @ styles.ts:372
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$Ej @ styles.ts:372
await in _$Ej (async)
requestUpdate @ styles.ts:372
u @ styles.ts:372
g @ styles.ts:372
k @ styles.ts:372
F @ ha-dialog.ts:125
E @ typography.js:181
t @ typography.js:181
(anonymous) @ ha-svg-icon.ts:44
Promise.then (async)
c @ ha-svg-icon.ts:44
(anonymous) @ ha-svg-icon.ts:44
i @ typography.js:181
c @ ha-energy-water-settings.ts:135
value @ ha-energy-grid-settings.ts:266
handleEvent @ styles.ts:372
ha-statistic-picker.ts:97 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at F.<anonymous> (ha-statistic-picker.ts:97:1)
    at F.i [as _getStatistics] (typography.js:181:1)
    at F.value (ha-statistic-picker.ts:97:1)
    at F.performUpdate (styles.ts:372:1)
    at F.scheduleUpdate (styles.ts:372:1)
    at F._$Ej (styles.ts:372:1)
(anonymous) @ ha-statistic-picker.ts:97
i @ typography.js:181
value @ ha-statistic-picker.ts:97
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$Ej @ styles.ts:372
await in _$Ej (async)
requestUpdate @ styles.ts:372
set @ styles.ts:372
value @ ha-statistic-picker.ts:255
handleEvent @ styles.ts:372
i @ typography.js:181
value @ ha-combo-box.ts:215
handleEvent @ styles.ts:372
O @ typography.js:181
D @ typography.js:181
P @ typography.js:181
(anonymous) @ typography.js:181
_propertiesChanged @ typography.js:181
_propertiesChanged @ vaadin-combo-box-scroller.js:52
_flushProperties @ typography.js:181
_invalidateProperties @ typography.js:181
Object.defineProperty.set @ typography.js:181
close @ vaadin-combo-box-scroller.js:52
value @ ha-combo-box.ts:215
handleEvent @ styles.ts:372
ha-statistic-picker.ts:97 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at F.<anonymous> (ha-statistic-picker.ts:97:1)
    at F.i [as _getStatistics] (typography.js:181:1)
    at F.value (ha-statistic-picker.ts:97:1)
    at F.performUpdate (styles.ts:372:1)
    at F.scheduleUpdate (styles.ts:372:1)
    at F._$Ej (styles.ts:372:1)
(anonymous) @ ha-statistic-picker.ts:97
i @ typography.js:181
value @ ha-statistic-picker.ts:97
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$Ej @ styles.ts:372
await in _$Ej (async)
requestUpdate @ styles.ts:372
set @ styles.ts:372
value @ ha-statistic-picker.ts:255
handleEvent @ styles.ts:372
i @ typography.js:181
value @ ha-combo-box.ts:215
handleEvent @ styles.ts:372
O @ typography.js:181
D @ typography.js:181
P @ typography.js:181
(anonymous) @ typography.js:181
_propertiesChanged @ typography.js:181
_propertiesChanged @ vaadin-combo-box-scroller.js:52
_flushProperties @ typography.js:181
_invalidateProperties @ typography.js:181
Object.defineProperty.set @ typography.js:181
close @ vaadin-combo-box-scroller.js:52
_closeOrCommit @ vaadin-combo-box-scroller.js:52
_onFocusout @ vaadin-combo-box-scroller.js:52
```

### Additional information

The error `cannot read properties of undefined (reading 'length')` seems to occur every time I click on the small triangle in the entity selection dialog

ha-statistic-picker.ts:97 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at F.<anonymous> (ha-statistic-picker.ts:97:1)
    at F.i [as _getStatistics] (typography.js:181:1)
    at F.value (ha-statistic-picker.ts:97:1)
    at F.performUpdate (styles.ts:372:1)
    at F.scheduleUpdate (styles.ts:372:1)
    at F._$Ej (styles.ts:372:1)

**Comment by tripplet** [comment]
The home assistant log showed the following error:
```
2023-02-06 19:40:00.187 ERROR (DbWorker_0) [homeassistant.components.recorder.util] Error executing query: 'NoneType' object has no attribute 'lower'
2023-02-06 19:40:00.189 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139751073585792] Error handling message: Unknown error (unknown_error) from 10.28.82.4 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/recorder/websocket_api.py", line 280, in ws_list_statistic_ids
    await ws_handle_list_statistic_ids(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/recorder/websocket_api.py", line 260, in ws_handle_list_statistic_ids
    await get_instance(hass).async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/recorder/websocket_api.py", line 251, in _ws_get_list_statistic_ids
    messages.result_message(msg_id, list_statistic_ids(hass, None, statistic_type))
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 939, in list_statistic_ids
    result = {
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 941, in <dictcomp>
    "display_unit_of_measurement": get_display_unit(
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 175, in get_display_unit
    if state := hass.states.get(statistic_id):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1381, in get
    return self._states.get(entity_id.lower())
AttributeError: 'NoneType' object has no attribute 'lower'
```

The problem was a row with NULL in the `statistics_meta` table of the database, after I removed it the bug is gone.
