### ISSUE TITLE
History Dashboard / RECORDER Invalid Entity ID

### ISSUE THREAD

**Issue by sca075** [home-assistant/frontend#15386]
### The problem

Logger: homeassistant.components.recorder.util
Source: components/recorder/util.py:130
Integration: Recorder ([documentation](https://www.home-assistant.io/integrations/recorder), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+recorder%22))
First occurred: 16:34:35 (5 occurrences)
Last logged: 16:37:13

Error executing query: Invalid entity ID esp

GUI issue, the recorder started to search an entity, instead to cancel the search it created the entity "esp" that was the key for the search function of the History Viewer. 
http://192.168.xxx.xxc:8123/history

### What version of Home Assistant Core has the issue?

Home Assistant 2023.2.1 Supervisor 2023.01.1 Frontend 20230202.0 

### What was the last working version of Home Assistant Core?

unknown

### What type of installation are you running?

Home Assistant Supervised

### Integration causing the issue

Recorder

### Link to integration documentation on our website

https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22

### Diagnostics information

Logger: homeassistant.components.websocket_api.http.connection
Source: core.py:160
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:34:35 (5 occurrences)
Last logged: 16:37:13

[140118256233600] Error handling message: Unknown error (unknown_error) from 192.168.158.228 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36)
[140118470969520] Error handling message: Unknown error (unknown_error) from 192.168.158.228 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36)
[140118470815520] Error handling message: Unknown error (unknown_error) from 192.168.158.228 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/history/websocket_api.py", line 443, in ws_stream
    await _async_send_historical_states(
  File "/usr/src/homeassistant/homeassistant/components/history/websocket_api.py", line 226, in _async_send_historical_states
    await get_instance(hass).async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 225, in get_significant_states
    return get_significant_states_with_session(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 364, in get_significant_states_with_session
    stmt = _significant_states_stmt(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 269, in _significant_states_stmt
    and split_entity_id(entity_ids[0])[0] not in SIGNIFICANT_DOMAINS
  File "/usr/src/homeassistant/homeassistant/core.py", line 160, in split_entity_id
    raise ValueError(f"Invalid entity ID {entity_id}")
ValueError: Invalid entity ID esp

### Example YAML snippet

```yaml
none.
```

### Anything in the logs that might be useful for us?

```txt
The History page (//homehassistant:8123/history) is in infinite loop. 
The error is generated, so why the search will not end? 
Reboot of the system to recovery this situation did not help.
Cleared Crome cash, new login to the front end and history page started to work again.
```

### Additional information

I really appreciate the functionalities provided with the several updates. 
History Dashboard was recently updated

**Comment by karwosts** [comment]
If you get stuck in this situation and can't get the history page back, one way I found to get out of it is to reset the entity_id via the URL, e.g. type in and hit enter:

http://homeassistant.local:8123/history?entity_id=zone.home

You can use any entity_id, zone.home was just an easy one for me to remember that I think should be valid for most people.

**Comment by karwosts** [comment]
No I don't know. Seems like even non-existant entities are fine, entering "x.x" as an entity correctly just quickly returns "No state history found". It's only when you enter an entity without a '.' that the core chokes when it tries to split out the domain. 

Seems like an exception is thrown in core when this occurs, but the attempt to "catch" it in frontend does not work. No idea how exceptions are supposed to be handled across the websocket.

**Comment by Jamie-McKernan** [comment]
I've just figured a simple way to fix it on mobile. Just go to the list of entities in settings, find something with some history and click "show more".

It'll take you to the history page with a working entity in the search filter.

**Comment by sca075** [comment]
It seams that somehow it is a kind of iteration between the frontend and the web browsers.. with Crome I had to clear the cash to get the query cleared. In other hands, as per no exception is raised due to the improper selection the browser will simply continue to query for the improper entity, unless.. you remove the query from the cash.  I do not know exactly if this is just a frontend or core issue. Anyhow this did not happen until the real time view of the entities status was introduced.

**Comment by wilwizard1979** [comment]
> If you get stuck in this situation and can't get the history page back, one way I found to get out of it is to reset the entity_id via the URL, e.g. type in and hit enter:
> 
> http://homeassistant.local:8123/history?entity_id=zone.home
> 
> You can use any entity_id, zone.home was just an easy one for me to remember that I think should be valid for most people.

This was a great workaround. It has fixed the issue for me.
Thanks a lot!!
