### ISSUE TITLE
Brand filter in add integration dialog does not work

### ISSUE THREAD

**Issue by carstenschroeder** [home-assistant/frontend#16376]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I try to filter by brand in the add integration dialog the list of brands is unchanged. 

After that I see the following error in the log:
http://192.168.0.?:8123/frontend_latest/92205-Otjy1Y-6Hhc.js:4:54510 Uncaught TypeError: r.startsWith is not a function

### Describe the behavior you expected

The list of brands should be filtered according to the entered search string.

### Steps to reproduce the issue

1. Go to Settings -> Devices & Services
2. Click on Add Integration button
3. Enter a search string in the search field of the dialog
4. The list of brands does not change
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.4.6 / Frontend 20230411.1 - latest

### What was the last working version of Home Assistant Core?

n/a

### In which browser are you experiencing the issue with?

Google Chrome 112.0.5615.138 (same in Android Home Assistant App)

### Which operating system are you using to run this browser?

Windows 11 22H2

### Javascript errors shown in your browser console/inspector
```
active-element.ts:1233 Uncaught (in promise) TypeError: r.startsWith is not a function
    at dialog-add-integration.ts:219:43
    at Array.forEach (<anonymous>)
    at i.<anonymous> (dialog-add-integration.ts:170:25)
    at i [as _filterIntegrations] (memoize-one.esm.js:37:35)
    at i.value (dialog-add-integration.ts:271:17)
    at i.value (dialog-add-integration.ts:285:14)
    at i.update (lit-element.ts:160:24)
    at i.performUpdate (reactive-element.ts:1331:14)
    at i.scheduleUpdate (reactive-element.ts:1263:17)
    at i._$Ej (reactive-element.ts:1235:25)


dialog-add-integration.ts:219 Uncaught (in promise) TypeError: r.startsWith is not a function
    at dialog-add-integration.ts:219:43
    at Array.forEach (<anonymous>)
    at i.<anonymous> (dialog-add-integration.ts:170:25)
    at i [as _filterIntegrations] (memoize-one.esm.js:37:35)
    at i.value (dialog-add-integration.ts:271:17)
    at i.value (dialog-add-integration.ts:285:14)
    at i.update (lit-element.ts:160:24)
    at i.performUpdate (reactive-element.ts:1331:14)
    at i.scheduleUpdate (reactive-element.ts:1263:17)
    at i._$Ej (reactive-element.ts:1235:25)
(
```

**Comment by piitaya** [comment]
Do you have custom integrations installed with hacs? If, yes, can you provide the list?

**Comment by carstenschroeder** [comment]
I have a couple of own custom integrations installed. Perhaps I missed something regarding brands. Could you give me a hint, what prerequisites my integrations have to meet?

**Comment by piitaya** [comment]
https://github.com/carstenschroeder/smappee_custom/blob/master/custom_components/smappee_custom/manifest.json

`iot_class` should be a string. In your case, it's an array. You can find possible value in the [dev documentation ](https://developers.home-assistant.io/docs/creating_integration_manifest/#iot-class)

**Comment by carstenschroeder** [comment]
@piitaya Thank you so much!
