### ISSUE TITLE
Select selector in dropdown-mode not shown in automation builder

### ISSUE THREAD

**Issue by farmio** [home-assistant/frontend#16455]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When defining a device trigger using a `selector.SelectSelector` the field is not shown if it is configured as dropdown through `mode="dropdown"` or `custom_value=True`.

### Describe the behavior you expected

I'd expect the dropdown to be shown.

### Steps to reproduce the issue

1. add a SelectSelector to device triggers
2. open the automation builder
3.
...

### What version of Home Assistant Core has the issue?

core-2023.6.0.dev0 / frontend 20230503.3 - latest

### In which browser are you experiencing the issue with?

Safari 16.4 / Chrome 112.0.5615.137

### Which operating system are you using to run this browser?

macOS Venture 13.3.1

### Javascript errors shown in your browser console/inspector

```txt
caught (in promise) TypeError: e.map is not a function
    at HTMLElement.value (ha-selector-select.ts:112:23)
    at HTMLElement.update (lit-element.ts:160:24)
    at HTMLElement.performUpdate (reactive-element.ts:1331:14)
    at HTMLElement.scheduleUpdate (reactive-element.ts:1263:17)
    at HTMLElement._$Ej (reactive-element.ts:1235:25)
value @ ha-selector-select.ts:112
update @ lit-element.ts:160
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
(anonym) @ dynamic-element-directive.ts:28
update @ dynamic-element-directive.ts:27
_$AS @ directive.ts:134
N @ lit-html.ts:1077
_$AI @ lit-html.ts:1350
v @ lit-html.ts:1180
g @ lit-html.ts:1525
_$AI @ lit-html.ts:1372
$ @ lit-html.ts:2168
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
j @ lit-html.ts:1868
_$AI @ lit-html.ts:1810
v @ lit-html.ts:1180
g @ lit-html.ts:1525
_$AI @ lit-html.ts:1372
v @ lit-html.ts:1180
g @ lit-html.ts:1525
_$AI @ lit-html.ts:1372
T @ lit-html.ts:1603
_$AI @ lit-html.ts:1391
v @ lit-html.ts:1180
g @ lit-html.ts:1525
_$AI @ lit-html.ts:1372
$ @ lit-html.ts:2168
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
j @ lit-html.ts:1868
_$AI @ lit-html.ts:1810
v @ lit-html.ts:1180
g @ lit-html.ts:1525
_$AI @ lit-html.ts:1372
v @ lit-html.ts:1180
g @ lit-html.ts:1525
_$AI @ lit-html.ts:1372
$ @ lit-html.ts:2168
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
(anonym) @ dynamic-element-directive.ts:28
update @ dynamic-element-directive.ts:27
_$AS @ directive.ts:134
N @ lit-html.ts:1077
_$AI @ lit-html.ts:1350
v @ lit-html.ts:1180
g @ lit-html.ts:1525
_$AI @ lit-html.ts:1372
v @ lit-html.ts:1180
g @ lit-html.ts:1525
_$AI @ lit-html.ts:1372
$ @ lit-html.ts:2168
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
j @ lit-html.ts:1868
_$AI @ lit-html.ts:1810
v @ lit-html.ts:1180
g @ lit-html.ts:1525
_$AI @ lit-html.ts:1372
p @ directive-helpers.ts:172
update @ repeat.ts:341
_$AS @ directive.ts:134
N @ lit-html.ts:1077
_$AI @ lit-html.ts:1350
v @ lit-html.ts:1180
g @ lit-html.ts:1525
_$AI @ lit-html.ts:1372
$ @ lit-html.ts:2168
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
j @ lit-html.ts:1868
_$AI @ lit-html.ts:1810
v @ lit-html.ts:1180
g @ lit-html.ts:1525
_$AI @ lit-html.ts:1372
$ @ lit-html.ts:2168
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
j @ lit-html.ts:1868
_$AI @ lit-html.ts:1810
v @ lit-html.ts:1180
g @ lit-html.ts:1525
_$AI @ lit-html.ts:1372
v @ lit-html.ts:1180
g @ lit-html.ts:1525
_$AI @ lit-html.ts:1372
v @ lit-html.ts:1180
g @ lit-html.ts:1525
_$AI @ lit-html.ts:1372
$ @ lit-html.ts:2168
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
value @ ha-config-automation.ts:77
value @ hass-router-page.ts:91
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
value @ ha-panel-config.ts:595
value @ hass-router-page.ts:91
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
value @ partial-panel-resolver.ts:112
value @ hass-router-page.ts:91
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
j @ lit-html.ts:1868
_$AI @ lit-html.ts:1810
v @ lit-html.ts:1180
g @ lit-html.ts:1525
_$AI @ lit-html.ts:1372
$ @ lit-html.ts:2168
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
j @ lit-html.ts:1868
_$AI @ lit-html.ts:1810
v @ lit-html.ts:1180
g @ lit-html.ts:1525
_$AI @ lit-html.ts:1372
$ @ lit-html.ts:2168
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
value @ hass-base-mixin.ts:52
_updateHass @ context-mixin.ts:95
(anonym) @ connection-mixin.ts:190
s @ store.js:19
(anonym) @ entities.js:74
e.subscribeMessage.type @ entities.js:76
(anonym) @ connection.js:23
_handleMessage @ connection.js:15
```

### Additional information

No error in HA core logs.

**Comment by karwosts** [comment]
Is there an existing integration that exhibits this, or are you developing something new in core?

If this doesn't currently exhibit anywhere, could you suggest a specific modification to a common component that would exhibit this? To make it easy to reproduce?

**Comment by farmio** [comment]
As far as I have seen, there is currently not a single integration in core using any selector for device triggers. 

I was just looking if selectors can be used there for the core `knx` integration. 

I'll see if I can build a demo - maybe tonight.

**Comment by farmio** [comment]
I have set up a demo with the `sun` integration and it worked as expected. When I went back to my working branch it also worked there then.

Sorry, this was a false alarm. Unfortunately I don't know what I did differently now and can't reproduce the error now 🙃
