### ISSUE TITLE
Media Control Card:  Error getting Image Colors

### ISSUE THREAD

**Issue by DigiLive** [home-assistant/frontend#16735]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The following errors get logged in the console when the Lovelace dashboard loads:

```console
07:47:39.270 GET
https://fcools.duckdns.org:8123/api/media_player_proxy/media_player.50pus8535_12_2?token=010a941759da7e813ae02673d6e858977cf2734012003db74645fd8bb697c71f&cache=5d79663e449b67a8

[HTTP/1.1 500 Internal Server Error 131ms]

07:47:39.519 Error getting Image Colors Error: Fail to load image: https://fcools.duckdns.org:8123/api/media_player_proxy/media_player.50pus8535_12_2?token=010a941759da7e813ae02673d6e858977cf2734012003db74645fd8bb697c71f&cache=5d79663e449b67a8
    onerror index.ts:86
    a index.ts:86
    load index.ts:75
    getPalette index.ts:69
    <anonymous> extract_color.ts:121
    value hui-media-control-card.ts:552
    value hui-media-control-card.ts:377
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1263
    _$Ej reactive-element.ts:1235
    requestUpdate reactive-element.ts:1210
    u reactive-element.ts:948
    g reactive-element.ts:931
    k lit-element.ts:115
    h hui-media-control-card.ts:47
    E scoped-custom-element-registry.js:385
    t scoped-custom-element-registry.js:236
    a create-element-base.ts:93
    u create-element-base.ts:140
    u create-element-base.ts:238
    d create-element-base.ts:172
    w create-card-element.ts:99
    value hui-stack-card.ts:102
    _cards hui-stack-card.ts:47
    value hui-stack-card.ts:46
    setConfig hui-grid-card.ts:62
    a create-element-base.ts:97
    u create-element-base.ts:242
    d create-element-base.ts:172
    w create-card-element.ts:99
    value hui-view.ts:64
    _cards hui-view.ts:283
    value hui-view.ts:282
    value hui-view.ts:216
    value hui-view.ts:130
    performUpdate reactive-element.ts:1329

hui-media-control-card.ts:558:14
```

### Describe the behavior you expected

No console errors.

### Steps to reproduce the issue

1. Open the browser's console.
2. Navigate to the Lovelace (auto-generated) dashboard with a media control card.
3. Inspect the console.

### What version of Home Assistant Core has the issue?

2023.04.1

### In which browser are you experiencing the issue with?

Firefox Developer Edition 114.0b9 (64 bits)

### Which operating system are you using to run this browser?

Windows 10 22H2 19045.2965

### Javascript errors shown in your browser console/inspector

```txt
07:47:39.270 GET
https://***.duckdns.org:8123/api/media_player_proxy/media_player.***?token=***&cache=***

[HTTP/1.1 500 Internal Server Error 131ms]

07:47:39.519 Error getting Image Colors Error: Fail to load image: https://***.duckdns.org:8123/api/media_player_proxy/media_player.***?token=***&cache=***
    onerror index.ts:86
    a index.ts:86
    load index.ts:75
    getPalette index.ts:69
    <anonymous> extract_color.ts:121
    value hui-media-control-card.ts:552
    value hui-media-control-card.ts:377
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1263
    _$Ej reactive-element.ts:1235
    requestUpdate reactive-element.ts:1210
    u reactive-element.ts:948
    g reactive-element.ts:931
    k lit-element.ts:115
    h hui-media-control-card.ts:47
    E scoped-custom-element-registry.js:385
    t scoped-custom-element-registry.js:236
    a create-element-base.ts:93
    u create-element-base.ts:140
    u create-element-base.ts:238
    d create-element-base.ts:172
    w create-card-element.ts:99
    value hui-stack-card.ts:102
    _cards hui-stack-card.ts:47
    value hui-stack-card.ts:46
    setConfig hui-grid-card.ts:62
    a create-element-base.ts:97
    u create-element-base.ts:242
    d create-element-base.ts:172
    w create-card-element.ts:99
    value hui-view.ts:64
    _cards hui-view.ts:283
    value hui-view.ts:282
    value hui-view.ts:216
    value hui-view.ts:130
    performUpdate reactive-element.ts:1329

hui-media-control-card.ts:558:14
```

**Comment by SpartanTech** [comment]
same issue as you!
hui-media-control-card.ts:558 Error getting Image Colors Error: Fail to load image:
 at e.complete.e.onerror (index.ts:86:35)

**Comment by DigiLive** [comment]
I didn't keep an eye on it, but it's still/again present.

Core 2023.11.2
Supervisor 2023.11.3
Operating System 11.1
Frontend 20231030.2

**Comment by PlantsThatsWhatsUp** [comment]
+1
`hui-media-control-card.ts:565  Error getting Image Colors Error: Fail to load image: http://homeassistant.local:8123/api/media_player_proxy/media_player.rx_v679_cfadac?token=TOKENHERE
    at e.complete.e.onerror (index.ts:86:35)`

My entire HA front-end hangs after awhile - not sure if related but can't seem to figure it out.

Core 2023.12.3
Supervisor 2023.12.0
Operating System 11.2
Frontend 20231208.2
