### ISSUE TITLE
2023.7.1 broke my Enphase connection

### ISSUE THREAD

**Issue by EdEgger** [home-assistant/frontend#17204]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

HA can't connect to my Envoy. Enlighten shows no problems and I can browse envoy.local
I reset the Envoy, the IP-number has not changed

Here is the log entry:

2023-07-07 14:02:10.762 ERROR (MainThread) [homeassistant.components.enphase_envoy] Unexpected error fetching envoy Envoy 122218047476 data: Could not connect or determine Envoy model. Check that the device is up at 'http://192.168.0.66'.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/enphase_envoy/__init__.py", line 44, in async_update_data
    await envoy_reader.getData()
  File "/usr/local/lib/python3.11/site-packages/envoy_reader/envoy_reader.py", line 136, in getData
    await self.detect_model()
  File "/usr/local/lib/python3.11/site-packages/envoy_reader/envoy_reader.py", line 209, in detect_model
    raise RuntimeError(
RuntimeError: Could not connect or determine Envoy model. Check that the device is up at 'http://192.168.0.66'.
2023-07-07 14:02:10.765 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Envoy 122218047476' for enphase_envoy integration not ready yet: Could not connect or determine Envoy model. Check that the device is up at 'http://192.168.0.66'.; Retrying in background

### Describe the behavior you expected

I expect no problems connecting to the Envoy

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.7.1

### What was the last working version of Home Assistant Core?

2023.7.0

### In which browser are you experiencing the issue with?

Safari 16.5.1 (18615.2.9.11.7)

### Which operating system are you using to run this browser?

macOS Ventura 13.4.1 (22F82)

**Comment by EdEgger** [comment]
I see it's a problem with the recent software update Enphase made to my Envoy
