### ISSUE TITLE
No sensor dropdown menu in energy dashboard / error of integration: Home Assistant WebSocket API

### ISSUE THREAD

**Issue by heikone** [home-assistant/frontend#17903]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I try to add a sensor in the energy dashboard, I'm facing the problem, that I can't see any drop down menu to select any sensor.
The dialogue looks like this:
<img width="425" alt="Bildschirmfoto 2023-09-11 um 21 24 25" src="https://github.com/home-assistant/frontend/assets/42500448/39548656-295c-406f-861a-d4ae23d5de9a">

I've noticed, that in the logs, an error occurs.
Refer to "additional information" if this issue for the error.

### Describe the behavior you expected

In past (but unsure when the dropdown menu disappeared), I was able to select any energy class sensor.

### Steps to reproduce the issue

Unsure how to reproduce this.

### What version of Home Assistant Core has the issue?

2023.9.1

### In which browser are you experiencing the issue with?

Apple Safari Version 16.6 (18615.3.12.11.2)

### Which operating system are you using to run this browser?

macOS Ventura 

### Additional information

Log error:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: core.py:1500 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 21:24:08 (4 occurrences) 
Last logged: 21:28:40

[140138009623360] Error handling message: Unknown error (unknown_error) Heiko from 88.153.88.137 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/recorder/websocket_api.py", line 334, in ws_get_statistics_metadata
    metadata = await async_list_statistic_ids(hass, statistic_ids_set_or_none)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 701, in async_list_statistic_ids
    return await instance.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 769, in list_statistic_ids
    result = _statistic_by_id_from_metadata(hass, metadata)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 714, in _statistic_by_id_from_metadata
    return {
           ^
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 716, in <dictcomp>
    "display_unit_of_measurement": get_display_unit(
                                   ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 185, in get_display_unit
    if state := hass.states.get(statistic_id):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1500, in get
    return self._states.get(entity_id.lower())
                            ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by karwosts** [comment]
I would suggest open a core issue against `recorder` integration and show them that error from the log. It seems like core is failing to return a list of statistics to the frontend. Maybe there is some corrupted entity in your database that's causing this.

**Comment by heikone** [comment]
Will try that

**Comment by karwosts** [comment]
core issue: 

Related: https://github.com/home-assistant/core/issues/100226
