### ISSUE TITLE
Switch Bot Bot button press mode On/Off

### ISSUE THREAD

**Issue by BrenTeck** [home-assistant/frontend#17911]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On sending a rest to turn on the Switch Bot Bot it times out / does not respond most of the time.

### Describe the behavior you expected

pressing the on or off button in the dashboard or using a service call does not work most of the time.
using the Swichbot app it will work with a bit of a delay and sometimes have to send the request twice but form HA almost never works.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.9.1

### In which browser are you experiencing the issue with?

HA app / Brave

### Which operating system are you using to run this browser?

Android 13 / win 11

### Javascript errors shown in your browser console/inspector

```txt
Log Details (ERROR)
Logger: homeassistant.components.websocket_api.http.connection
Source: components/switchbot/entity.py:99
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10 September 2023 at 09:39:01 (5 occurrences)
Last logged: 14:27:30

[547814949952] WoHand (MACaddress) - MACaddress: Failed to connect after 4 attempt(s): TimeoutError
[547805765440] MACaddress (MACaddress) - MACaddress: Failed to connect after 4 attempt(s): TimeoutError
[547793270080] WoHand (MACaddress) - MACaddress: Failed to connect after 5 attempt(s): TimeoutError
[547814066496] WoHand (MACaddress) - MACaddress: Failed to connect after 4 attempt(s): TimeoutError
[547817067712] MACaddress (MACaddress) - MACaddress: Failed to connect after 4 attempt(s): TimeoutError
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 209, in connect
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dbus_fast/aio/message_bus.py", line 390, in call
    await future
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 350, in establish_connection
    await client.connect(
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/wrappers.py", line 292, in connect
    connected = await super().connect(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/__init__.py", line 605, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak/backends/bluezdbus/client.py", line 146, in connect
    async with async_timeout(timeout):
  File "/usr/local/lib/python3.11/asyncio/timeouts.py", line 111, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 227, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1969, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2006, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/switchbot/entity.py", line 99, in async_turn_on
    self._last_run_success = bool(await self._device.turn_on())
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/switchbot/devices/device.py", line 96, in _async_update_after_operation_wrap
    ret = await func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/switchbot/devices/bot.py", line 37, in turn_on
    result = await self._send_command(ON_KEY)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/switchbot/devices/device.py", line 180, in _send_command
    return await self._send_command_locked(key, command)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/switchbot/devices/device.py", line 414, in _send_command_locked
    await self._ensure_connected()
  File "/usr/local/lib/python3.11/site-packages/switchbot/devices/device.py", line 274, in _ensure_connected
    client: BleakClientWithServiceCache = await establish_connection(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 374, in establish_connection
    _raise_if_needed(name, device.address, exc)
  File "/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py", line 314, in _raise_if_needed
    raise BleakNotFoundError(msg) from exc
bleak_retry_connector.BleakNotFoundError: WoHand (MACaddress) - MACaddress: Failed to connect after 4 attempt(s): TimeoutError
```

### Additional information

I hope I filled this in properly the first time I submitted a bug report. Thank you for all your work.

**Comment by karwosts** [comment]
Hi, `frontend` is the wrong repository for this issue. Suggest filing it in `core` :  https://github.com/home-assistant/core/issues/

That says it seems like maybe HA just can't connect to the switchbot, so maybe it's just a problem of bluetooth range, but I don't really know.
