### ISSUE TITLE
Invalid Fan Mode error when switching HVAC mode

### ISSUE THREAD

**Issue by RobertD502** [home-assistant/frontend#19620]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When switching from an HVAC mode with a Fan speed (fan_mode) of `Auto` to a HVAC mode that only supports a fan speed of `Auto`, an error message pops up indicating `Fan mode is not valid. Valid fan modes are: auto`.

For example, if the climate entity is currently in HVAC mode `Heat` with a Fan mode of `Auto`, when switching to a HVAC mode that only supports a single Fan Mode (Auto), such as Dry or Heat/Cool in my case, the error pops up in the UI.

**Video example shown below**
 

https://github.com/home-assistant/frontend/assets/52541649/db8dc9b3-cc6f-4355-a901-ef3dad0bdb7f

Note: This behavior only happens when switching from a HVAC mode that supports multiple fan modes in addition to the Auto mode, but not when switching from a HVAC mode that only supports an Auto fan_mode to another HVAC mode that only supports an Auto fan_mode (i.e., Going from Dry mode with a Fan mode of Auto to a HVAC mode of Heat/Cool).

Related `async_set_hvac_mode` code below:
```python
            if hvac_mode in [HVACMode.DRY, HVACMode.HEAT_COOL]:
                # When switching to Dry or Heat_Cool (Auto) mode,
                # a fan speed of Auto is expected

                mode_attributes = self.set_attributes('hvac_mode', mode, False)
                flair_speed = HASS_HVAC_FAN_SPEED_TO_FLAIR.get(FAN_AUTO)
                if self.hvac_data.attributes['fan-speed'] != flair_speed:
                    fan_attributes = self.set_attributes('fan_mode', flair_speed, False)
                    await self.coordinator.client.update('hvac-units', self.hvac_data.id, attributes=mode_attributes, relationships={})
                    await self.coordinator.client.update('hvac-units', self.hvac_data.id, attributes=fan_attributes, relationships={})
                    self.hvac_data.attributes['fan-speed'] = flair_speed
                else:
                    await self.coordinator.client.update('hvac-units', self.hvac_data.id, attributes=mode_attributes, relationships={})

                self.hvac_data.attributes['mode'] = mode
                self.async_write_ha_state()
                await self.coordinator.async_request_refresh()
                return None
```
As you can see, I am not setting `self.hvac_data.attributes['fan-speed']` to `flair_speed` (which results in the fan_mode property returning the Home Assistant `FAN_AUTO` constant) prior to writing the HA state when the current fan mode is already Auto.

During my debugging of the error, I have identified that the Climate `fan_mode` property is correctly returning `auto` prior to calling `self.async_write_ha_state()`, after calling `self.async_write_ha_state()`, and after a refresh is requested from the coordinator. With all of this said, the error seems to be contradicting the actual state of the fan_mode property.

### Describe the behavior you expected

When switching from an HVAC mode (which supports multiple fan modes) with a fan mode of Auto, to a HVAC mode that only supports a fan mode of Auto, no error message should be presented.

### Steps to reproduce the issue

1. Start with climate entity in a HVAC mode that supports multiple fan modes (auto, high, medium, low).
2. Ensure the climate entity has a current fan mode of `Auto`.
3. Change the HVAC mode to a HVAC mode that only supports `Auto` as its fan mode.
...

### What version of Home Assistant Core has the issue?

2024.2.0b2

### Additional information

![image](https://github.com/home-assistant/frontend/assets/52541649/77a00d3f-7d03-428d-91a4-f8c783897318)

**Comment by ChristophCaina** [comment]
I have similar issues with my Thermostats when i Change between "Auto", "heating" and "Off"...

**Comment by RobertD502** [comment]
Still an issue in the latest `20240705.0` frontend.

**Comment by fuguiKz** [comment]
same problem when use third Plug-in “bemfa”,
```
2024-07-07 12:22:01.175 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 406, in post
    await shield(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 731, in async_handle_set_fan_mode_service
    self._valid_mode_or_raise("fan", fan_mode, self.fan_modes)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 701, in _valid_mode_or_raise
    raise ServiceValidationError(
homeassistant.exceptions.ServiceValidationError: Fan mode HIGH is not valid. Valid fan modes are: Silent, Low, Medium, High, Full, Auto
```
![image](https://github.com/home-assistant/frontend/assets/74097723/eabb4b15-c608-4345-a20a-325b9890d2d3)

**Comment by karwosts** [comment]
I'm able to reproduce a similar effect by messing in developer tools. E.g. load up the `climate.ecobee` more-info from the demo integration.

Has the following fan modes, with default set to `on_high`

```
fan_modes:
  - on_low
  - on_high
  - auto_low
  - auto_high
  - "off"
```

While the more info is open, in developer tools in a separate window change the attribute fan modes to this:
```
fan_modes:
  - on_high
```

The fan mode control becomes bugged and it sends the invalid service call.

I guess the dropdown does not like it when it is selected to a particular index, and then the number of options changes to be less than that index, it resets the control to undefined and triggers a spurious service call.  Same with any of the other dropdowns.

**Comment by RobertD502** [comment]
Bump

**Comment by nchieffo** [comment]
I'm also affected, adding a comment as requested above

**Comment by RobertD502** [comment]
bump

**Comment by kevindbeard** [comment]
This is still an issue for me. Using the standard thermostat card to select one of the presets from the dropdown
