### ISSUE TITLE
Can't access the Devices & services page 

### ISSUE THREAD

**Issue by ddechamb** [home-assistant/frontend#21514]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Can't access the Devices & services page anymore

### Describe the behavior you expected

Perpetual loading wheel when tring to open the page

<img width="1331" alt="Screenshot 2024-07-31 at 22 08 04" src="https://github.com/user-attachments/assets/7fc0ac93-764c-47a9-a480-07676da25fe4">

### Steps to reproduce the issue

1. click settings
2. click on Devices & services
3.
...

### What version of Home Assistant Core has the issue?

2024.7.4

### What was the last working version of Home Assistant Core?

2024.7.4

### In which browser are you experiencing the issue with?

Google chrome  126.0.6478.185

### Which operating system are you using to run this browser?

macOS sonoma 14.3.1

### Additional information

I was setting up an automation, and the presence simulation addon. I restarted HA and it happened. 

I tried restoring the last core version, and everything else. Nothing happens.

**Comment by ddechamb** [comment]
Update on this: I went to bed frustrated and convinced I will have to reinstall everything from scratch in the morning. 
Today the page is working again, as if nothing happened.

**Comment by ddechamb** [comment]
It happened again just now. I can't access the page anymore.

**Comment by silamon** [comment]
Anything in the developer console, when you have the issue?

**Comment by ddechamb** [comment]
Here are my logs, I hope this can help! 

[home-assistant_2024-08-01T17-13-10.662Z.log](https://github.com/user-attachments/files/16459813/home-assistant_2024-08-01T17-13-10.662Z.log)

**Comment by silamon** [comment]
I've actually meant javascript errors shown in your browser console/inspector, but the log you provided shows the problem. 

Your issue is related to one of the integrations "swiss_public_transport", and probably very much related to https://github.com/home-assistant/core/issues/119137 but I would open a new one at https://github.com/home-assistant/core towards that integration. 

2024-08-01 18:21:28.756 ERROR (MainThread) [opendata_transport] Response from transport.opendata.ch: 429, message='Too Many Requests', url=URL('http://transport.opendata.ch/v1/connections?from=K%C3%BCsnacht+ZH&to=Z%C3%BCrich+HB&limit=3&page=0&isArrivalTime=0&direct=0&sleeper=0&couchette=0&bike=0')
2024-08-01 18:21:35.270 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140183641710528] Error handling message: Unknown error (unknown_error) David de Chambrier from 192.168.0.16 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/json.py", line 61, in json_encoder_default
    raise TypeError
TypeError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 531, in config_entries_subscribe
    current_entries = await _async_matching_config_entries_json_fragments(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 577, in _async_matching_config_entries_json_fragments
    entry.as_json_fragment
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 494, in as_json_fragment
    return json_fragment(json_bytes(json_repr))
                         ^^^^^^^^^^^^^^^^^^^^^
TypeError: Type is not JSON serializable: OpendataTransportConnectionError

That error you've got there in the logs should be response what you get on the page, but it's failing there so it keeps loading and loading.

**Comment by silamon** [comment]
The fact you're being rate limited by their api is also the answer to why it works sometimes and sometimes not.

**Comment by ddechamb** [comment]
I see and therefore it explains why it works in the morning, when the rate limitation gets restarted! Thanks a ton for your help!

**Comment by silamon** [comment]
I'm going to reopen the issue, since I think it should not break things in the frontend.
