### ISSUE TITLE
After last HA update (2024.9) on iOS, scripts from widgets do not work

### ISSUE THREAD

**Issue by vladbaja** [home-assistant/frontend#21999]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The buttons on my desktop widgets worked until last Home Assistant update. After that, the widget flicker after clicking any button that points to a script.
I tried reinstalling the phone app (it somehow knows the state of widgets since before uninstalling, thing I find weird).
I see some error logs:

Logger: homeassistant.components.mobile_app.webhook
Source: components/mobile_app/webhook.py:291
integration: Mobile App
First occurred: 10:15:38 PM (2 occurrences)
Last logged: 10:15:38 PM

Error when calling service during mobile_app webhook (device name: Vlad): Action script.2da17a4e3b4a4144917a71f699adf80d-priza_1_min not found

and

Logger: homeassistant.components.webhook
Source: components/webhook/__init__.py:192
integration: Webhook ()
First occurred: 10:15:38 PM (2 occurrences)
Last logged: 10:15:38 PM

Error processing webhook 855a4d99d03cba3cac8d039f97f6a93b0b733c50149dbf6e99553f91f48d5ce6

Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 283, in webhook_call_service await hass.services.async_call( File "/usr/src/homeassistant/homeassistant/core.py", line 2694, in async_call raise ServiceNotFound(domain, service) from None homeassistant.exceptions.ServiceNotFound: Action script.2da17a4e3b4a4144917a71f699adf80d-priza_1_min not found The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 192, in async_handle_webhook response: Response | None = await webhook["handler"](hass, webhook_id, request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 265, in handle_webhook return await asyncio.shield( ^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 175, in validate_and_run return await func(hass, config_entry, data) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 299, in webhook_call_service raise HTTPBadRequest from ex aiohttp.web_exceptions.HTTPBadRequest: Bad Request

### Describe the behavior you expected

Clicking the button on the widget must run the script.

### Steps to reproduce the issue

On last HomeAssistant on iOS and iOS version 17.7, create a script and place a widget on desktop with the script. Press the button on the widget. The widget flickers. The script is not run. In the logs there is something similar with what I posted above.

### What version of Home Assistant Core has the issue?

iPhone with iOS 17.8 and HA 2009.9

### In which browser are you experiencing the issue with?

on iOS widget

### Which operating system are you using to run this browser?

iOS

**Comment by karwosts** [comment]
This seems like maybe something you'll need to report to the iOS repository. 

https://github.com/home-assistant/iOS/issues

**Comment by vladbaja** [comment]
Fixed in 2024.9.1

**Comment by Eoras** [comment]
I think is needeed to re-open this ticket beacause got same issue last IOS vers and last HA APP version
