### ISSUE TITLE
Shelly integration becomes unavailable randomly

### ISSUE THREAD

**Issue by rpanachi** [home-assistant/frontend#22699]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Shelly integration for Shelly Pro 3EM becomes unavailable randomly (works fine and suddenly crashes, showing 'Failed to load' on Integrations settings.

### Describe the behavior you expected

Works without any intermittency 

### Steps to reproduce the issue

The problem occurs without any reason or action

### What version of Home Assistant Core has the issue?

2024.10.4

### Additional information

2024-11-06 16:15:01.979 INFO (MainThread) [aioshelly.rpc_device.wsrpc] Connected to fd1f:ea34:770f:6831:3698:7aff:fe68:fa0
2024-11-06 16:15:02.043 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry shellypro3em-34redacted0fa0 for shelly
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/yarl/_url.py", line 191, in __new__
    port = val.port
           ^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'ea34:770f:6831:3698:7aff:fe68:fa0:80'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/shelly/__init__.py", line 129, in async_setup_entry
    return await _async_setup_rpc_entry(hass, entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/shelly/__init__.py", line 266, in _async_setup_rpc_entry
    shelly_entry_data.rpc.async_setup()
  File "/usr/src/homeassistant/homeassistant/components/shelly/coordinator.py", line 689, in async_setup
    super().async_setup(pending_platforms)
  File "/usr/src/homeassistant/homeassistant/components/shelly/coordinator.py", line 142, in async_setup
    device_entry = dev_reg.async_get_or_create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 663, in async_get_or_create
    configuration_url = _validate_configuration_url(configuration_url)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 234, in _validate_configuration_url
    url = value if type(value) is URL else _cached_parse_url(url_as_str)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yarl/_url.py", line 193, in __new__
    raise ValueError(
ValueError: Invalid URL: port can't be converted to integer

**Comment by karwosts** [comment]
Please file this in home-assistant/core, this is not a frontend issue.
