### ISSUE TITLE
Beta 2025.1.0b0 Setup Backup Button Causing Page to hang till refreshed

### ISSUE THREAD

**Issue by jweston2112** [home-assistant/frontend#23424]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I click the button Setup Backup Button and then I can't click anything until I refresh the page

Browser Console contains the Following
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'logged_in')
    at F.value (dialog-backup-onboarding.ts:104:34)
    at l (make-dialog-manager.ts:137:17)
value @ dialog-backup-onboarding.ts:104
l @ make-dialog-manager.ts:137
await in l
(anonymous) @ make-dialog-manager.ts:215
r @ fire_event.ts:75
(anonymous) @ show-dialog-backup_onboarding.ts:19
o @ show-dialog-backup_onboarding.ts:16
value @ ha-config-backup-overview.ts:81
value @ ha-config-backup-overview.ts:77
handleEvent @ lit-html.ts:2018
r @ fire_event.ts:75
value @ ha-backup-overview-onboarding.ts:24
handleEvent @ lit-html.ts:2018
```
### Describe the behavior you expected

I would assume a Dialog box would be displayed

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.1.0b0

### What was the last working version of Home Assistant Core?

2024.12.5

### In which browser are you experiencing the issue with?

Brave 1.73.91 and Microsoft Edge 131.0.2903.112

### Which operating system are you using to run this browser?

Kubuntu 24.10 kernel 6.11.0 KDE Plasma 6 wayland 

### Javascript errors shown in your browser console/inspector

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'logged_in')
    at F.value (dialog-backup-onboarding.ts:104:34)
    at l (make-dialog-manager.ts:137:17)
value @ dialog-backup-onboarding.ts:104
l @ make-dialog-manager.ts:137
await in l
(anonymous) @ make-dialog-manager.ts:215
r @ fire_event.ts:75
(anonymous) @ show-dialog-backup_onboarding.ts:19
o @ show-dialog-backup_onboarding.ts:16
value @ ha-config-backup-overview.ts:81
value @ ha-config-backup-overview.ts:77
handleEvent @ lit-html.ts:2018
r @ fire_event.ts:75
value @ ha-backup-overview-onboarding.ts:24
handleEvent @ lit-html.ts:2018
```

### Additional information

I downgraded and reupgraded rebooted the PI and Cleared cache and relogged in to HA prior to trying again to access the Backup Page I also get the same result in safe mode.

**Comment by jweston2112** [comment]
Still Happening in 2025.1.0b1
