### ISSUE TITLE
Error rising temperature of knx climate control in lovelace

### ISSUE THREAD

**Issue by wwillm** [home-assistant/frontend#4912]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
When rising any of my **knx climate** controls, an error is raised:
Log: expected float for dictionary value @ data['temperature']
After this happened, the given temperature is not shown any more until restart (reload) of lovelace

Very seldom: If I decrease the temperate, no error will be rised

## Expected behavior

 Increase the temperature control

## Steps to reproduce

  For example:
    1. Add a knx climate integration
    2. Navigate to Lovelace
    3. Open the climate entity
    4. Set the temperature higher than the shown temperature
    5. The temperature level disappears and shows : **°C**

    

## Environment
  Home Assistant frontend: Developer tools -> Info.
  Home Assistant 0.105.4

  Any browser will have this error

- Home Assistant release with the issue:  0.105.4
- Last working Home Assistant release (if known):  Never
- UI Type (States or Lovelace):  Lovelace
- Browser and browser version: Any browser
- Operating system: Windows and android

## Problem-relevant configuration
  configuration example:
```yaml
  - platform: knx
    name: Wohnzimmer-Temperatur
    temperature_address: '2/0/200'
    target_temperature_state_address: '2/0/201'
    target_temperature_address: '2/0/203'
```

## Javascript errors shown in your browser console/inspector
```txt
MultipleInvalid: expected float for dictionary value @ data['temperature']
```

## Additional information
Here is the relevant log entry:
```txt
Mon Feb 17 2020 12:09:36 GMT+0100 (Mitteleuropäische Normalzeit)
expected float for dictionary value @ data['temperature']
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1204, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 208, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 287, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 283, in _exec
    v = func(v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 205, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 287, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 285, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected float for dictionary value @ data['temperature']
```

**Comment by bramkragten** [comment]
This KNX specific, please create an issue for the KNX integration.
