### ISSUE TITLE
media-control album art issues

### ISSUE THREAD

**Issue by i00** [home-assistant/frontend#5341]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

1. When the album art changes the album art disappears for a second then fades to the new one
1. When the art from async_get_media_image goes from:
return imagedata, imagedatamimetype _to_
return None, None
... you end up with something like this:
![image](https://user-images.githubusercontent.com/1435262/77602168-78a36200-6f58-11ea-82c2-f29ab632b4e4.png)

## Expected behavior

1. It should get the new album art then fade between them
1. The faded rectangle from the previous album art should not be shown

## Environment

- Home Assistant release with the issue: 0.107.6
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome
- Operating system: Windows 10

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by i00** [comment]
Sill an issue

**Comment by glyndon** [comment]
Similar problem here, but it only began on upgrade to 115.x.
No cover art at all, media control card is a uniform light blue.
This happens when the player is a chromecast and the source is Pandora.
When media begin playing, the following appears in the log:

`Logger: aiohttp.server
Source: components/media_player/__init__.py:850
First occurred: September 25, 2020, 7:28:20 AM (245 occurrences)
Last logged: 9:42:12 AM

Error handling request
Traceback (most recent call last):
  File "/srv/venv3.7.3/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/srv/venv3.7.3/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/srv/venv3.7.3/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/venv3.7.3/lib/python3.7/site-packages/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/srv/venv3.7.3/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/srv/venv3.7.3/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/srv/venv3.7.3/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/srv/venv3.7.3/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py", line 894, in get
    data, content_type = await player.async_get_media_image()
  File "/srv/venv3.7.3/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py", line 425, in async_get_media_image
    return await _async_fetch_image(self.hass, url)
  File "/srv/venv3.7.3/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py", line 850, in _async_fetch_image
    response = await websession.get(url)
  File "/srv/venv3.7.3/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/srv/venv3.7.3/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/srv/venv3.7.3/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/srv/venv3.7.3/lib/python3.7/site-packages/aiohttp/connector.py", line 963, in _create_direct_connection
    assert port is not None
AssertionError
`
