### ISSUE TITLE
device_class on binary sensor not changing state text in UI

### ISSUE THREAD

**Issue by Alfiegerner** [home-assistant/frontend#5701]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem
Upgrading from 108 and now on 109.2 my binary_sensors with device_class are showing state on or off rather then e.g. locked, open, closed

![image](https://user-images.githubusercontent.com/596188/80851841-27ce0a00-8c78-11ea-9c1e-24af6de87fe2.png)

All custom components in their own folder:

![image](https://user-images.githubusercontent.com/596188/80851866-5cda5c80-8c78-11ea-8d44-ba41f5dff084.png)

## Expected behavior
binary_sensors with device class should display relevant state description, e.g. open / closed rather than on / off.

The icons are correct, just the text.

## Steps to reproduce
Updrade and view binary_sensor with a device class. 

## Environment
109.2 Venv running on ubuntu.

- Home Assistant release with the issue:
- Last working Home Assistant release (if known): 108.x
- Browser and browser version: Chome 81
- Operating system: Ubuntu 18.04

## State of relevant entities

```yaml

```
Example state from 2 sensors reporting on / off in UI
![image](https://user-images.githubusercontent.com/596188/80852075-aa0afe00-8c79-11ea-8948-e677acea5dcc.png)

## Problem-relevant configuration
These sensors are zigbee or zwave, auto added by intergration with no other config.

```yaml

```

## Javascript errors shown in your browser console/inspector

![image](https://user-images.githubusercontent.com/596188/80852120-1ede3800-8c7a-11ea-99fb-6f253c4934fc.png)

![image](https://user-images.githubusercontent.com/596188/80852152-72e91c80-8c7a-11ea-933e-78ebf86e5d3c.png)

**Comment by Alfiegerner** [comment]
Found this error in the logs:

```
2020-05-02 15:37:38 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139796891135040] Error handling message: Unknown error
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/websocket_api/decorators.py", line 20, in _handle_async_response
    await func(hass, connection, msg)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/frontend/__init__.py", line 545, in websocket_get_translations
    resources = await async_get_translations(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/translation.py", line 329, in async_get_translations
    resources = flatten(resource_func(results[0], components, category))
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/translation.py", line 127, in merge_resources
    new_value = translation_strings[component].get(category)
KeyError: 'climate.sensibo'
2020-05-02 15:37:38 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139796892848240] Error handling message: Unknown error
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/websocket_api/decorators.py", line 20, in _handle_async_response
    await func(hass, connection, msg)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/frontend/__init__.py", line 545, in websocket_get_translations
    resources = await async_get_translations(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/translation.py", line 329, in async_get_translations
    resources = flatten(resource_func(results[0], components, category))
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/translation.py", line 127, in merge_resources
    new_value = translation_strings[component].get(category)
KeyError: 'climate.sensibo'
```

**Comment by Alfiegerner** [comment]
Quick hacky fix:

edit  /srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/translation.py, line 127 to  catch exception:
```
        try:
          new_value = translation_strings[component].get(category)
        except:
          print('''transaltion exception''')
          new_value = None

```
And everything is working again:

![image](https://user-images.githubusercontent.com/596188/80854907-fc571980-8c8f-11ea-877b-05fcf957f96d.png)

**Comment by Alfiegerner** [comment]
'climate.senibo' refers to a local custom_component.  I tried adding a translations/en.json in the custom_component folder with this:

```
{
  "common": {
     "climate.sensibo": "climate.sensibo"
  }
}
```

But no dice.

**Comment by bramkragten** [comment]
Fixed by https://github.com/home-assistant/core/pull/35032
