### ISSUE TITLE
Dashboards not loading after upgrade

### ISSUE THREAD

**Issue by SebRut** [home-assistant/frontend#6045]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

After upgrading from 0.109 to 0.110 two of my dashboards do not load anymore. The following error is shown for one dashboard:

`Expecting value: line 133 column 21 (char 6083)`

## Expected behavior

My dashboards should load.

## Environment

- Home Assistant release with the issue: 0.110.2
- Last working Home Assistant release (if known): 0.109.x
- Browser and browser version: Chrome 83.0.4103.61
- Operating system: Manjaro Linux

## Problem-relevant configuration

config of dashboard (`.storage/lovelace.lovelace_nesthub`)
```json
{
    "data": {
        "config": {
            "title": "Zuhause",
            "views": [
                {
                    "badges": [],
                    "cards": [
                        {
                            "entity": "weather.dark_sky",
                            "type": "weather-forecast"
                        },
                        {
                            "entities": [
                                {
                                    "entity": "input_number.comfort_temperature"
                                },
                                {
                                    "entity": "input_number.eco_temperature"
                                }
                            ],
                            "show_header_toggle": false,
                            "type": "entities"
                        },
                        {
                            "entities": [
                                {
                                    "entity": "vacuum.staubi",
                                    "tap_action": {
                                        "action": "call-service",
                                        "service": "automation.trigger",
                                        "service_data": {
                                            "entity_id": "automation.automatisches_saugen"
                                        }
                                    }
                                },
                                {
                                    "entity": "switch.kaffeemaschine",
                                    "icon": "mdi:coffee",
                                    "tap_action": {
                                        "action": "call-service",
                                        "service": "switch.toggle",
                                        "service_data": {
                                            "entity_id": "switch.kaffeemaschine"
                                        }
                                    }
                                }
                            ],
                            "type": "glance"
                        },
                        {
                            "entities": [
                                {
                                    "entity": "sensor.aleas_geburtstag"
                                },
                                {
                                    "entity": "sensor.sebastians_geburtstag"
                                },
                                {
                                    "entity": "sensor.matchday"
                                }
                            ],
                            "title": "Save The Dates",
                            "type": "glance"
                        },
                        {
                            "entities": [
                                {
                                    "entity": "light.kueche",
                                    "tap_action": {
                                        "action": "call-service",
                                        "service": "light.toggle",
                                        "service_data": {
                                            "entity_id": "light.kueche"
                                        }
                                    }
                                }
                            ],
                            "type": "glance"
                        },
                    ],
                    "path": "default_nesthub_view",
                    "title": "HomeAssistant"
                }
            ]
        }
    },
    "key": "lovelace.lovelace_nesthub",
    "version": 1
}
```
## Additional information
logs output:
```
2020-05-25 18:56:07 ERROR (SyncWorker_4) [homeassistant.util.json] Could not parse JSON content: /hassconf/.storage/lovelace.lovelace_nesthub
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/util/json.py", line 32, in load_json
    return json.loads(fdesc.read())  # type: ignore
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 81 column 21 (char 3551)
```

**Comment by bramkragten** [comment]
And you didn't touch the json yourself?

You should remove the `,` on line 81

**Comment by SebRut** [comment]
Oh wow, I feel stupid now :D I removed an entry and checked with https://jsonformatter.curiousconcept.com/. Seems like just ignored that additional `,`.
