### ISSUE TITLE
Calling Service that calls script by button behaves differently than calling by dev tool

### ISSUE THREAD

**Issue by maweki** [home-assistant/frontend#7726]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
I am not sure whether this issue is core or frontend. I have a script that can be correctly called using the dev tools:

![image](https://user-images.githubusercontent.com/613272/99555016-210ea680-29c0-11eb-8212-cf371a478fa3.png)

This works and my heating starts correctly.

I have a button in a hoirzontal stack with a config that should do exactly the same:

```YAML
          - type: button
            show_name: false
            icon: "mdi:thermometer-chevron-up"
            tap_action:
              action: call-service
              service: script.turn_on
              service-data:
                entity_id: script.climate_boost
                variables:
                  room: arbeitszimmer
```

But pressing the button leads to an `must contain at least one of entity_id, area_id.` error (traceback below). It seems like the service data may not be transported (maybe the variables aren't).

## Expected behavior

The button should behave the same as the dev tool.

## Environment

- Home Assistant release with the issue: 0.117.6
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome for Linux, Firefox Mobile
- Operating system: Linux, Android

## Problem-relevant configuration

```YAML
          - type: button
            show_name: false
            icon: "mdi:thermometer-chevron-up"
            tap_action:
              action: call-service
              service: script.turn_on
              service-data:
                entity_id: script.climate_boost
                variables:
                  room: arbeitszimmer
```

And for reference the script:

```YAML
climate_boost:
  fields:
    room:
      description: 'Raum'
      example: 'arbeitszimmer'
  sequence:
    - service: climate.set_preset_mode
      data:
        entity_id: "climate.{{ room }}"
        preset_mode: boost
```

## Javascript errors shown in your browser console/inspector

```txt
app.8efb5ced.js:41533 Uncaught (in promise) {code: "unknown_error", message: "must contain at least one of entity_id, area_id."}
callService @ app.8efb5ced.js:41533
async function (async)
callService @ app.8efb5ced.js:41533
l @ chunk.cdf43a32e306acfdb2f4.js:322
value @ chunk.c23d64825d253b823e6e.js:2309
handleEvent @ app.8efb5ced.js:10288
__boundHandleEvent @ app.8efb5ced.js:10288
i @ app.8efb5ced.js:10288
e.actionHandler.t.disabled.e.actionHandler.end @ chunk.c98b2a84446f6a63360d.js:2045
```

## Additional information

Traceback of the error:

```txt
Traceback (most recent call last):
  File "/srv/hass/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/srv/hass/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/helpers/config_validation.py", line 129, in validate
    raise vol.Invalid("must contain at least one of {}.".format(", ".join(keys)))
voluptuous.error.Invalid: must contain at least one of entity_id, area_id.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/core.py", line 1402, in async_call
    processed_data = handler.schema(service_data)
  File "/srv/hass/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/srv/hass/lib/python3.8/site-packages/voluptuous/validators.py", line 340, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/srv/hass/lib/python3.8/site-packages/voluptuous/validators.py", line 336, in _exec
    v = func(v)
  File "/srv/hass/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: must contain at least one of entity_id, area_id.
```

**Comment by maweki** [comment]
Okay, this can be reproduced even simpler:

create a script. You can use the UI, that does anything:

```yaml
alias: Testscript
sequence:
  - service: notify.persistent_notification
    data:
      message: The garage door has been open for 10 minutes.
      title: Your Garage Door Friend
mode: single
```

Have a lovelace dashboard with a button that should call it:

```yaml
views:
  - badges: []
    cards:
      - type: button
        tap_action:
          action: call-service
          service: script.turn_on
          service-data:
            entity_id: script.testscript
```

This leads to the error `must contain at least one of entity_id, area_id.`, while calling `script.turn_on` through dev-tools works.

**Comment by maweki** [comment]
It's `service_data`, not `service-data`.
