### ISSUE TITLE
Unable to call the input_select.select_option service from a button

### ISSUE THREAD

**Issue by Corneloues** [home-assistant/frontend#8026]
It is impossible to call the `input_select.select_option` service from a button.

Using the UI designer first, and then dropping to manual as `data:` is not supported. I end up with the following:

```
type: button
tap_action:
  action: call-service
  service: input_select.select_option
  data:
    option: bright
entity: light.office
```

I have tried, with help, to format the YAML a number of ways, but all without success. The only option that works is to use the `call-service` action to execute a script:

```
office_off:
  alias: Office (Off)
  sequence:
  - service: input_select.select_option
    data:
      option: 'off'
    entity_id: input_select.office_light_state
  mode: single
  icon: mdi:power-on

type: button
tap_action:
  action: call-service
  service: script.office_off
entity: light.office
name: 'Off'
icon: 'mdi:power-on'
```

This combination would not be necessary if I could simply call the `input_select.select.option` service from a button.

**Comment by frenck** [comment]
Lovelace (frontend) configuration differs slightly from the backend (core) configuration.

`data` isn't a valid option in the frontend (it is in the backend). In the frontend this is called `service_data`:

```yaml
type: button
tap_action:
  action: call-service
  service: input_select.select_option
  service_data:
    option: bright
entity: light.office
```

**Comment by Corneloues** [comment]
I'm sure we tried that. Let me go again and I'll come back and let you know

**Comment by Corneloues** [comment]
Here's the button:

```
type: button
tap_action:
  action: call-service
  service: input_select.select_option
  service_data:
    option: two
entity: input_select.test_service_helper
name: One
```

Here's the error:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/config_validation.py:140
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:11:28 (4 occurrences)
Last logged: 21:11:40

[548346961680] sequence item 0: expected str instance, Optional found
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1399, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 336, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/helpers/config_validation.py", line 140, in validate
    raise vol.Invalid("must contain at least one of {}.".format(", ".join(keys)))
TypeError: sequence item 0: expected str instance, Optional found
```

**Comment by Corneloues** [comment]
![Uploading image.png…]()

**Comment by RomRider** [comment]
You are missing the `entity_id` in `service_data`, that's why it's complaining. ;)

**Comment by Corneloues** [comment]
Tried that. It didn't work.

```
type: button
tap_action:
  service: input_select.select_option
  data:
    option: 'off'
    entity_id: light.bedroom_4
entity: light.bedroom_4
name: 'Off'
icon: 'mdi:power-on'
```

**Comment by Corneloues** [comment]
And whether you use `data:` or `service_data:` it still doesn't work.

**Comment by RomRider** [comment]
Your config is still wrong: the `entity_id` for an `input_select.select_option` can't be a light.

```yaml
type: button
tap_action:
  service: input_select.select_option
  data:
    option: 'off'
    entity_id: input_select.test_service_helper
entity: light.bedroom_4
name: 'Off'
icon: 'mdi:power-on'
```

**Comment by Corneloues** [comment]
The light entity is for the button.

The entity_id is for the service call.

**Comment by RomRider** [comment]
You didn't read properly my message. The `entity_id` for the service call needs to be a type `input_select` which is not the case in what you pasted but is corrected in my message. 🤷‍♂️

**Comment by Corneloues** [comment]
Thanks, I thought you were posting my code back...

It appears to be working now, so I'll see how it goes.

**Comment by Corneloues** [comment]
This is now working as expected. The nuances of `data:` and `service-data:` are what confused me.

It would be great if the Yaml was little more consistent as I see no need for the differences.

I'll close this report now.
