### ISSUE TITLE
Error in logs after migrating to ZWaveJS for TZ-67 Wall Plug

### ISSUE THREAD

**Issue by foxy82** [home-assistant/frontend#8429]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

I have migrated from a working Openzwave installation to ZWaveJS using the ZWaveJS2MQTT add on.

I am now seeing this error in my logs for my TZ67 Wall plug

```txt
2021-02-21 14:59:22 ERROR (MainThread) [homeassistant.helpers.event] Error while processing state changed for light.all_graysons_room_lights_group
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 257, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 435, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 960, in _refresh
    self.hass.async_run_hass_job(self._job, event, updates)
  File "/usr/src/homeassistant/homeassistant/core.py", line 435, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 248, in _handle_results
    attr.handle_result(
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 87, in handle_result
    self.on_update(result)
  File "/usr/src/homeassistant/homeassistant/components/template/light.py", line 369, in _update_brightness
    if 0 <= int(brightness) <= 255:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Describe the behavior you expected**

I don't expect to see an error in the logs.

**Steps to reproduce the issue**

Not sure - I was turning the light on/off

**What version of Home Assistant Core has the issue?**

core-2021.2.3

**What was the last working version of Home Assistant Core?**

Using OpenZWave

**In which browser are you experiencing the issue with?**

Google Chrome

**Which operating system are you using to run this browser?**

Windows 10

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

```yaml
# Paste your YAML here.

```

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.

```

**Comment by frenck** [comment]
This is not a frontend issue. If you want to report an issue with an integration, please report it here:

<https://github.com/home-assistant/core/issues>

Thanks 👍
 
../Frenck
