### ISSUE TITLE
[2021.3.0b0] Addons have no config

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/frontend#8464]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

When I go to an addon configuration tab, the config element is just empty. See screenshots

**Describe the behavior you expected**

Show config panel

**Steps to reproduce the issue**

1. Go to supervisor panel
2. Go to an addon
3. Select the configuration tab

**What version of Home Assistant Core has the issue?**

2021.3.0b0

**What was the last working version of Home Assistant Core?**

2021.02.x

**In which browser are you experiencing the issue with?**

Microsoft Edge 89.0.774.34

**Which operating system are you using to run this browser?**

Windows 10 20H2

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

```yaml
# Paste your YAML here.

```

**Javascript errors shown in your browser console/inspector**

```txt
service_worker.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://my.domain/?homescreen=1","error":{}}]
    at $.handle (https://my.domain/service_worker.js:1:14885)
t @ service_worker.js:1
handle @ service_worker.js:1
entrypoint.5c3eb78c.js:75351 GET https://my.domain/api/hassio/app/frontend_latest/chunk.1904870317d0d8638977.js net::ERR_ABORTED 504
n.l @ entrypoint.5c3eb78c.js:75351
n.f.j @ entrypoint.5c3eb78c.js:75351
(anonymous) @ entrypoint.5c3eb78c.js:75351
n.e @ entrypoint.5c3eb78c.js:75351
ut @ chunk.608800a294b1d02a0765.js:2589
value @ chunk.608800a294b1d02a0765.js:2589
value @ chunk.608800a294b1d02a0765.js:2589
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
k @ entrypoint.5c3eb78c.js:35547
r @ chunk.608800a294b1d02a0765.js:2589
_clone @ entrypoint.5c3eb78c.js:35547
__commitTemplateResult @ entrypoint.5c3eb78c.js:35547
commit @ entrypoint.5c3eb78c.js:35547
a @ entrypoint.5c3eb78c.js:35547
M.render @ entrypoint.5c3eb78c.js:35547
update @ entrypoint.5c3eb78c.js:35547
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
k @ entrypoint.5c3eb78c.js:35547
M @ entrypoint.5c3eb78c.js:35547
F @ chunk.608800a294b1d02a0765.js:2589
_clone @ entrypoint.5c3eb78c.js:35547
__commitTemplateResult @ entrypoint.5c3eb78c.js:35547
commit @ entrypoint.5c3eb78c.js:35547
update @ entrypoint.5c3eb78c.js:35547
__commitTemplateResult @ entrypoint.5c3eb78c.js:35547
commit @ entrypoint.5c3eb78c.js:35547
a @ entrypoint.5c3eb78c.js:35547
M.render @ entrypoint.5c3eb78c.js:35547
update @ entrypoint.5c3eb78c.js:35547
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
k @ entrypoint.5c3eb78c.js:35547
M @ entrypoint.5c3eb78c.js:35547
r @ chunk.608800a294b1d02a0765.js:3137
_clone @ entrypoint.5c3eb78c.js:35547
__commitTemplateResult @ entrypoint.5c3eb78c.js:35547
commit @ entrypoint.5c3eb78c.js:35547
update @ entrypoint.5c3eb78c.js:35547
__commitTemplateResult @ entrypoint.5c3eb78c.js:35547
commit @ entrypoint.5c3eb78c.js:35547
update @ entrypoint.5c3eb78c.js:35547
__commitTemplateResult @ entrypoint.5c3eb78c.js:35547
commit @ entrypoint.5c3eb78c.js:35547
a @ entrypoint.5c3eb78c.js:35547
M.render @ entrypoint.5c3eb78c.js:35547
update @ entrypoint.5c3eb78c.js:35547
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
k @ entrypoint.5c3eb78c.js:35547
M @ entrypoint.5c3eb78c.js:35547
F @ chunk.608800a294b1d02a0765.js:3818
value @ entrypoint.5c3eb78c.js:73572
value @ entrypoint.5c3eb78c.js:73572
_currentLoadProm.l.then._currentLoadProm @ entrypoint.5c3eb78c.js:73572
Promise.then (async)
value @ entrypoint.5c3eb78c.js:73572
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
k @ entrypoint.5c3eb78c.js:35547
r @ entrypoint.5c3eb78c.js:73572
F @ chunk.608800a294b1d02a0765.js:5837
_clone @ entrypoint.5c3eb78c.js:35547
__commitTemplateResult @ entrypoint.5c3eb78c.js:35547
commit @ entrypoint.5c3eb78c.js:35547
a @ entrypoint.5c3eb78c.js:35547
M.render @ entrypoint.5c3eb78c.js:35547
update @ entrypoint.5c3eb78c.js:35547
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
set @ entrypoint.5c3eb78c.js:35547
value @ chunk.608800a294b1d02a0765.js:6186
async function (async)
value @ chunk.608800a294b1d02a0765.js:6186
value @ chunk.608800a294b1d02a0765.js:6186
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
k @ entrypoint.5c3eb78c.js:35547
M @ entrypoint.5c3eb78c.js:35547
F @ chunk.608800a294b1d02a0765.js:5837
value @ entrypoint.5c3eb78c.js:73572
value @ entrypoint.5c3eb78c.js:73572
_currentLoadProm.l.then._currentLoadProm @ entrypoint.5c3eb78c.js:73572
Promise.then (async)
value @ entrypoint.5c3eb78c.js:73572
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
requestUpdate @ entrypoint.5c3eb78c.js:35547
(anonymous) @ entrypoint.5c3eb78c.js:73572
Promise.then (async)
value @ entrypoint.5c3eb78c.js:73572
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
k @ entrypoint.5c3eb78c.js:35547
r @ entrypoint.5c3eb78c.js:73572
F @ entrypoint.5c3eb78c.js:82205
_clone @ entrypoint.5c3eb78c.js:35547
__commitTemplateResult @ entrypoint.5c3eb78c.js:35547
commit @ entrypoint.5c3eb78c.js:35547
a @ entrypoint.5c3eb78c.js:35547
M.render @ entrypoint.5c3eb78c.js:35547
update @ entrypoint.5c3eb78c.js:35547
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
set @ entrypoint.5c3eb78c.js:35547
value @ entrypoint.5c3eb78c.js:82205
async function (async)
value @ entrypoint.5c3eb78c.js:82205
value @ entrypoint.5c3eb78c.js:82205
value @ entrypoint.5c3eb78c.js:82205
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
k @ entrypoint.5c3eb78c.js:35547
M @ entrypoint.5c3eb78c.js:35547
(anonymous) @ entrypoint.5c3eb78c.js:82205
Si @ entrypoint.5c3eb78c.js:82205
i @ entrypoint.5c3eb78c.js:82205
n @ entrypoint.5c3eb78c.js:82205
finisher @ entrypoint.5c3eb78c.js:35547
runClassFinishers @ entrypoint.5c3eb78c.js:82205
(anonymous) @ entrypoint.5c3eb78c.js:82205
(anonymous) @ entrypoint.5c3eb78c.js:82205
(anonymous) @ entrypoint.5c3eb78c.js:82751
(anonymous) @ entrypoint.5c3eb78c.js:82751
entrypoint.5c3eb78c.js:75351 GET https://my.domain/api/hassio/app/frontend_latest/chunk.fc63da2f89234a1a9014.js net::ERR_ABORTED 504
n.l @ entrypoint.5c3eb78c.js:75351
n.f.j @ entrypoint.5c3eb78c.js:75351
(anonymous) @ entrypoint.5c3eb78c.js:75351
n.e @ entrypoint.5c3eb78c.js:75351
ut @ chunk.608800a294b1d02a0765.js:2589
value @ chunk.608800a294b1d02a0765.js:2589
value @ chunk.608800a294b1d02a0765.js:2589
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
k @ entrypoint.5c3eb78c.js:35547
r @ chunk.608800a294b1d02a0765.js:2589
_clone @ entrypoint.5c3eb78c.js:35547
__commitTemplateResult @ entrypoint.5c3eb78c.js:35547
commit @ entrypoint.5c3eb78c.js:35547
a @ entrypoint.5c3eb78c.js:35547
M.render @ entrypoint.5c3eb78c.js:35547
update @ entrypoint.5c3eb78c.js:35547
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
k @ entrypoint.5c3eb78c.js:35547
M @ entrypoint.5c3eb78c.js:35547
F @ chunk.608800a294b1d02a0765.js:2589
_clone @ entrypoint.5c3eb78c.js:35547
__commitTemplateResult @ entrypoint.5c3eb78c.js:35547
commit @ entrypoint.5c3eb78c.js:35547
update @ entrypoint.5c3eb78c.js:35547
__commitTemplateResult @ entrypoint.5c3eb78c.js:35547
commit @ entrypoint.5c3eb78c.js:35547
a @ entrypoint.5c3eb78c.js:35547
M.render @ entrypoint.5c3eb78c.js:35547
update @ entrypoint.5c3eb78c.js:35547
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
k @ entrypoint.5c3eb78c.js:35547
M @ entrypoint.5c3eb78c.js:35547
r @ chunk.608800a294b1d02a0765.js:3137
_clone @ entrypoint.5c3eb78c.js:35547
__commitTemplateResult @ entrypoint.5c3eb78c.js:35547
commit @ entrypoint.5c3eb78c.js:35547
update @ entrypoint.5c3eb78c.js:35547
__commitTemplateResult @ entrypoint.5c3eb78c.js:35547
commit @ entrypoint.5c3eb78c.js:35547
update @ entrypoint.5c3eb78c.js:35547
__commitTemplateResult @ entrypoint.5c3eb78c.js:35547
commit @ entrypoint.5c3eb78c.js:35547
a @ entrypoint.5c3eb78c.js:35547
M.render @ entrypoint.5c3eb78c.js:35547
update @ entrypoint.5c3eb78c.js:35547
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
k @ entrypoint.5c3eb78c.js:35547
M @ entrypoint.5c3eb78c.js:35547
F @ chunk.608800a294b1d02a0765.js:3818
value @ entrypoint.5c3eb78c.js:73572
value @ entrypoint.5c3eb78c.js:73572
_currentLoadProm.l.then._currentLoadProm @ entrypoint.5c3eb78c.js:73572
Promise.then (async)
value @ entrypoint.5c3eb78c.js:73572
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
k @ entrypoint.5c3eb78c.js:35547
r @ entrypoint.5c3eb78c.js:73572
F @ chunk.608800a294b1d02a0765.js:5837
_clone @ entrypoint.5c3eb78c.js:35547
__commitTemplateResult @ entrypoint.5c3eb78c.js:35547
commit @ entrypoint.5c3eb78c.js:35547
a @ entrypoint.5c3eb78c.js:35547
M.render @ entrypoint.5c3eb78c.js:35547
update @ entrypoint.5c3eb78c.js:35547
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
set @ entrypoint.5c3eb78c.js:35547
value @ chunk.608800a294b1d02a0765.js:6186
async function (async)
value @ chunk.608800a294b1d02a0765.js:6186
value @ chunk.608800a294b1d02a0765.js:6186
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
k @ entrypoint.5c3eb78c.js:35547
M @ entrypoint.5c3eb78c.js:35547
F @ chunk.608800a294b1d02a0765.js:5837
value @ entrypoint.5c3eb78c.js:73572
value @ entrypoint.5c3eb78c.js:73572
_currentLoadProm.l.then._currentLoadProm @ entrypoint.5c3eb78c.js:73572
Promise.then (async)
value @ entrypoint.5c3eb78c.js:73572
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
requestUpdate @ entrypoint.5c3eb78c.js:35547
(anonymous) @ entrypoint.5c3eb78c.js:73572
Promise.then (async)
value @ entrypoint.5c3eb78c.js:73572
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
k @ entrypoint.5c3eb78c.js:35547
r @ entrypoint.5c3eb78c.js:73572
F @ entrypoint.5c3eb78c.js:82205
_clone @ entrypoint.5c3eb78c.js:35547
__commitTemplateResult @ entrypoint.5c3eb78c.js:35547
commit @ entrypoint.5c3eb78c.js:35547
a @ entrypoint.5c3eb78c.js:35547
M.render @ entrypoint.5c3eb78c.js:35547
update @ entrypoint.5c3eb78c.js:35547
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
set @ entrypoint.5c3eb78c.js:35547
value @ entrypoint.5c3eb78c.js:82205
async function (async)
value @ entrypoint.5c3eb78c.js:82205
value @ entrypoint.5c3eb78c.js:82205
value @ entrypoint.5c3eb78c.js:82205
performUpdate @ entrypoint.5c3eb78c.js:35547
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
async function (async)
_enqueueUpdate @ entrypoint.5c3eb78c.js:35547
requestUpdateInternal @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
initialize @ entrypoint.5c3eb78c.js:35547
k @ entrypoint.5c3eb78c.js:35547
M @ entrypoint.5c3eb78c.js:35547
(anonymous) @ entrypoint.5c3eb78c.js:82205
Si @ entrypoint.5c3eb78c.js:82205
i @ entrypoint.5c3eb78c.js:82205
n @ entrypoint.5c3eb78c.js:82205
finisher @ entrypoint.5c3eb78c.js:35547
runClassFinishers @ entrypoint.5c3eb78c.js:82205
(anonymous) @ entrypoint.5c3eb78c.js:82205
(anonymous) @ entrypoint.5c3eb78c.js:82205
(anonymous) @ entrypoint.5c3eb78c.js:82751
(anonymous) @ entrypoint.5c3eb78c.js:82751
entrypoint.5c3eb78c.js:75351 Uncaught (in promise) ChunkLoadError: Loading chunk 360 failed.
(error: https://my.domain/api/hassio/app/frontend_latest/chunk.1904870317d0d8638977.js)
    at Object.n.f.j (https://my.domain/api/hassio/app/frontend_latest/entrypoint.5c3eb78c.js:3912:2353)
    at https://my.domain/api/hassio/app/frontend_latest/entrypoint.5c3eb78c.js:3912:802
    at Array.reduce (<anonymous>)
    at Function.n.e (https://my.domain/api/hassio/app/frontend_latest/entrypoint.5c3eb78c.js:3912:780)
    at ut (https://my.domain/api/hassio/app/frontend_latest/chunk.608800a294b1d02a0765.js:476:141)
    at HTMLElement.value (https://my.domain/api/hassio/app/frontend_latest/chunk.608800a294b1d02a0765.js:476:10056)
    at HTMLElement.value (https://my.domain/api/hassio/app/frontend_latest/chunk.608800a294b1d02a0765.js:476:9982)
    at HTMLElement.performUpdate (https://my.domain/api/hassio/app/frontend_latest/entrypoint.5c3eb78c.js:2736:171050)
    at HTMLElement._enqueueUpdate (https://my.domain/api/hassio/app/frontend_latest/entrypoint.5c3eb78c.js:2736:170561)
```

![Screenshot_2021 02 25_21h58m29s_001_](https://user-images.githubusercontent.com/1368405/109216280-9efafe80-77b4-11eb-933a-2f23f6d9c48f.png)

![Screenshot_2021 02 25_22h00m38s_002_](https://user-images.githubusercontent.com/1368405/109216617-0b75fd80-77b5-11eb-8eb4-763d7a9253ac.png)

**Comment by TheZoker** [comment]
For some reason it works again, so I'll close this

**Comment by Claw256** [comment]
I am having the same error, what did you do to fix this?
