### ISSUE TITLE
HA not loading within iFrame

### ISSUE THREAD

**Issue by eglia** [home-assistant/frontend#9114]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I access my Home Assistant from Organizr, which embeds it within an iFrame.
Since the update to 2021.5.0, Home Assistant no longer loads within the iFrame (errors see below). Accessing Home Assistant directly works normally. Organizr and Home Assistant are on separate subdomains (organizr.mydomain.com & home-assistant.mydomain.com).
Everything is served through an nginx reverse proxy, which sets a CSP:
`add_header Content-Security-Policy "frame-ancestors 'self' *.mydomain.com;";`
I also tried to add the `Access-Control-Allow-Origin` header, but with no effect.
A few days ago, the supervisor panel already started having the same problem after the supervisor was automatically updated.

### Describe the behavior you expected

Home Assistant should load within an iFrame.

### Steps to reproduce the issue

1. Embed Home Assistant in an iFrame.
2. Attempt to open it.

### What version of Home Assistant Core has the issue?

2021.5.0

### What was the last working version of Home Assistant Core?

2021.4.6

### In which browser are you experiencing the issue with?

Firefox 88.0

### Which operating system are you using to run this browser?

Windows 10

### Javascript errors shown in your browser console/inspector

```txt
Uncaught DOMException: Permission denied to access property "addEventListener" on cross-origin object app.780f338b.js:1276
    connectedCallback https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:1276
    finisher https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    runClassFinishers https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:1409
    <anonymous> https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:1409
    <anonymous> https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:1409
    <anonymous> https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:1420
    <anonymous> https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:1420
    InnerModuleEvaluation self-hosted:2379
    evaluation self-hosted:2330
Uncaught (in promise) DOMException: Permission denied to access property "history" on cross-origin object app.780f338b.js:849
    value https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:1420
    InterpretGeneratorResume self-hosted:1480
    AsyncFunctionNext self-hosted:690
    (Async: async)
    handleEvent https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    __boundHandleEvent https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    x https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    E https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    w https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    _propertiesChanged https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    _propertiesChanged https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    _flushProperties https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    _flushProperties https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    _invalidateProperties https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    _setProperty https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    set https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    _locationChanged https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:1271
    R https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    w https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    _ https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    _propertiesChanged https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    _flushProperties https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    _flushProperties https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    _invalidateProperties https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    _propertiesChanged https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    _propertiesChanged https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    _flushProperties https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    _flushProperties https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    _invalidateProperties https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    _setProperty https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    set https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    paramsStringChanged https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:1271
    A https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
    w https://home-assistant.mydomain.com/frontend_latest/app.780f338b.js:849
```

**Comment by bramkragten** [comment]
Thanks for reporting, we are aware of the issue and how to solve it.

**Comment by thegame3202** [comment]
> Thanks for reporting, we are aware of the issue and how to solve it.

Awesome! If you need any testing or additional logs, I'm happy to help. Thank you!

**Comment by krystiancharubin** [comment]
Still experiencing this issue on 2021.5.3

**Comment by Nick4-1** [comment]
I run into this problem as well...

**Comment by CJA85** [comment]
Also have this issue after upgrading to core-2021.5.5

**Comment by Morphy99** [comment]
I'm having a similar issue with onboarding using an iframe:

```
Uncaught (in promise) DOMException: Blocked a frame with origin "http://192.168.0.195:8081" from accessing a cross-origin frame.
    at Object.72055 (http://192.168.0.195:8081/frontend_latest/onboarding.59a126ca.js:1297:129501)
    at a (http://192.168.0.195:8081/frontend_latest/onboarding.59a126ca.js:1869:1335)
    at Object.74265 (http://192.168.0.195:8081/frontend_latest/onboarding.59a126ca.js:1345:2288)
    at a (http://192.168.0.195:8081/frontend_latest/onboarding.59a126ca.js:1869:1335)
    at Object.33005 (http://192.168.0.195:8081/frontend_latest/onboarding.59a126ca.js:1345:63549)
    at a (http://192.168.0.195:8081/frontend_latest/onboarding.59a126ca.js:1869:1335)
    at http://192.168.0.195:8081/frontend_latest/onboarding.59a126ca.js:1869:10300
    at http://192.168.0.195:8081/frontend_latest/onboarding.59a126ca.js:1869:10310
```

Is this related or should I open a new issue?

**Comment by bramkragten** [comment]
That looks like a different issue, so yes, please open a new one.
