### ISSUE TITLE
New error in supervisor

### ISSUE THREAD

**Issue by NGRaposo** [home-assistant/frontend#9214]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

21-05-20 11:09:53 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1003' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=TypeError('an integer is required (got type str)')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 416, in _watchdog_addon_application
    if addon.in_progress or await addon.watchdog_application():
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 479, in watchdog_application
    return await self.sys_run_in_executor(check_port, self.ip_address, port)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 43, in check_port
    result = sock.connect_ex((str(address), port))
TypeError: an integer is required (got type str)

### Describe the behavior you expected

dont no

### Steps to reproduce the issue

1.
2.
3.
...
dont no

### What version of Home Assistant Core has the issue?

core-2021.5.5

**Comment by NGRaposo** [comment]
I run homeassistant in a raspberry pi4 with external ssd, and i have a stick deconZ
