### ISSUE TITLE
recorder_database_migration failed

### ISSUE THREAD

**Issue by aureliosaraiva** [home-assistant/frontend#9305]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Database migration is failing, and several services are starting to crash.

### Describe the behavior you expected

Should migrate correctly

### Steps to reproduce the issue

1. docker pull (last version)
2. HA start
3. start update
4. fail update
...

### What version of Home Assistant Core has the issue?

core-2021.5.5

### What was the last working version of Home Assistant Core?

2021.4

### Which operating system are you using to run this browser?

Ubunto server

### Additional information

![image](https://user-images.githubusercontent.com/118861/120115844-05007480-c15c-11eb-8741-5c7096373637.png)

```
Logger: homeassistant.components.recorder
Source: components/recorder/migration.py:263
Integration: Recorder (documentation, issues)
First occurred: 13:49:06 (1 occurrences)
Last logged: 13:49:06

Error during schema migration
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 587, in _migrate_schema_and_setup_run
    migration.migrate_schema(self, current_version)
  File "/usr/src/homeassistant/homeassistant/components/recorder/migration.py", line 64, in migrate_schema
    _apply_update(instance.engine, session, new_version, current_version)
  File "/usr/src/homeassistant/homeassistant/components/recorder/migration.py", line 417, in _apply_update
    _modify_columns(connection, engine, "events", ["event_type VARCHAR(64)"])
  File "/usr/src/homeassistant/homeassistant/components/recorder/migration.py", line 263, in _modify_columns
    connection.execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1258, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 320, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1447, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1664, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 556, in _revalidate_connection
    self._invalid_transaction()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 528, in _invalid_transaction
    raise exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back. (Background on this error at: http://sqlalche.me/e/14/8s2b)

```

**Comment by bramkragten** [comment]
This belongs in the core repo, not the frontend

**Comment by bramkragten** [comment]
And when opening an issue there, include what database you are using and other config.
