### ISSUE TITLE
Unknown Error for changes under persons

### ISSUE THREAD

**Issue by tidde88** [home-assistant/frontend#9387]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If I change something under "People" for example the picture or the device which should be tracked, the message "Unknown Error" appears. 

Under Core I find the following error message

"2021-06-07 14:02:45 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140437584550880] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 509, in ws_update_item
    item = await self.storage_collection.async_update_item(item_id, data)
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 265, in async_update_item
    await self.notify_changes(
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 141, in notify_changes
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 370, in _collection_changed
    for entity in await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 350, in _update_entity
    await entities[change_set.item_id].async_update_config(change_set.item)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/person/__init__.py", line 456, in async_update_config
    self._unsub_track_device = async_track_state_change_event(
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 253, in async_track_state_change_event
    entity_callbacks = hass.data.setdefault(TRACK_STATE_CHANGE_CALLBACKS, {})
AttributeError: 'NoneType' object has no attribute 'data'
2021-06-07 14:07:55 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140437584301888] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 509, in ws_update_item
    item = await self.storage_collection.async_update_item(item_id, data)
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 265, in async_update_item
    await self.notify_changes(
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 141, in notify_changes
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 370, in _collection_changed
    for entity in await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 350, in _update_entity
    await entities[change_set.item_id].async_update_config(change_set.item)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/person/__init__.py", line 456, in async_update_config
    self._unsub_track_device = async_track_state_change_event(
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 253, in async_track_state_change_event
    entity_callbacks = hass.data.setdefault(TRACK_STATE_CHANGE_CALLBACKS, {})
AttributeError: 'NoneType' object has no attribute 'data'"

### Describe the behavior you expected

That I can change images and the device to track

### Steps to reproduce the issue

1.Open "Persons"
2. Change Tracked Device
3. Click "save"
...

### What version of Home Assistant Core has the issue?

core-2021.6.2

### In which browser are you experiencing the issue with?

Chrome Chrome, Firefox

### Which operating system are you using to run this browser?

Windows 10

**Comment by spacegaier** [comment]
It seems in your example the backend/core raised an exception. I just tested it in my dev instance and cannot reproduce it. When I change the image for a person, everything works fine.

Can you please check if the issue still occurs for you in the latest stable version?
