### ISSUE TITLE
Cards suddenly reloading from scratch on device wakeup ("Connection Lost. Reconnecting...")

### ISSUE THREAD

**Issue by habitoti** [home-assistant/frontend#9407]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am running an old [Nexus tablet as a wall mounted dashboard ](https://www.reddit.com/r/homeassistant/comments/nnj4tv/my_pv_dashboard_in_my_kitchen_second_life_for_an/?utm_source=share&utm_medium=web2x&context=3)(Android 5.01, "naked" after factory reset). It runs under a specific user that has just access to one single dashboard. It is remotely woken up through a rest call from HA on motion detection of a sensor close by after it went to sleep (using "Wallpanel" kiosk app/Android WebView wrapper). The device is disconnected from the internet and its setup does not change through any updates. This worked w/o any issues until beginning of this week. But now all of a sudden, when the device wakes up a small "Connection lost. Reconnecting..." popup shortly shows and then the views are reloaded. As I have three expensive Grafana charts on that pretty old device, reloading them from scratch takes almost a minute. So just having a quick glance when walking by is no longer possible. 
As the device has no access to internet, nothing on that end has changed in any way. Only the remote HA instance is always timely updated, beginning of this week to latest core, supervisor etc. 
I switched off closing connections on sleep in user profile on the device for a try, however it makes no difference. I haven't touched that setting earlier (didn't even know about it's existence...). 
This doesn't happen always, but in around 4 out of 5 cases (wakeups).

### Describe the behavior you expected

Before the latest updates, the device just woke up and the dashboard did no fresh reload (neither completely nor per card). It just continued its regular updating of the data w/o having to start from scratch, which is specifically expensive for Grafana charts. 

### Steps to reproduce the issue

1. Put a device to sleep with a dashboard running 
2. Wake device up. 
3. Most often, cards or whole screen completely reloads (rather than just update data)

### What version of Home Assistant Core has the issue?

core-2021.6.3

### In which browser are you experiencing the issue with?

Chrome WebView 89.0.4389.105

### Which operating system are you using to run this browser?

Android 5.01

### Problem-relevant frontend configuration

```yaml
See link on top of this post. 3 Grafana views, expensive to initially load.
```

**Comment by habitoti** [comment]
Additional info: updated to latest WebView (91.0.4472.88), but no change in behaviour whatsoever...

**Comment by habitoti** [comment]
On the server log, the following issue sometimes shows up in parallel:

```
2021-06-14 14:44:38 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 76, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 45, in get
return await WebSocketHandler(request.app["hass"], request).async_handle()
File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 238, in async_handle
await self._writer_task
File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 81, in _writer
await self.wsock.send_str(message)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_ws.py", line 300, in send_str
await self._writer.send(data, binary=False, compress=compress)
File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 687, in send
await self._send_frame(message, WSMsgType.TEXT, compress)
File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 656, in _send_frame
await self.protocol._drain_helper()
File "/usr/local/lib/python3.8/site-packages/aiohttp/base_protocol.py", line 87, in _drain_helper
await waiter
File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 935, in _write_ready
n = self._sock.send(self._buffer)
BrokenPipeError: [Errno 32] Broken pipe
2021-06-14 14:45:31 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 673, in ping
await self._send_frame(message, WSMsgType.PING)
File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 650, in _send_frame
self._write(header + message)
File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 660, in _write
raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```
