### ISSUE TITLE
Error enabling analytics when /etc/passwd not populated

### ISSUE THREAD

**Issue by dbaker-rh** [home-assistant/frontend#9800]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

New HA installation, running 2021.8.6

When starting with a fresh configuration, I cannot proceed past an early stage of the initial signup *IF* I elect to submit analytics and I don't have a matching entry in /etc/passwd

### Describe the behavior you expected

Trying to enable analytics generates an error in the front end.  Back end log shows:

2021-08-13 15:38:36 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140280460553856] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/analytics/__init__.py", line 71, in websocket_analytics_preferences
    await analytics.send_analytics()
  File "/usr/src/homeassistant/homeassistant/components/analytics/analytics.py", line 153, in send_analytics
    system_info = await async_get_system_info(self.hass)
  File "/usr/src/homeassistant/homeassistant/helpers/system_info.py", line 26, in async_get_system_info
    "user": getuser(),
  File "/usr/local/lib/python3.9/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 8123'

I am running in a containerized environment, as non-root (uid=8123), but without /etc/passwd mapping this to a username.

### Steps to reproduce the issue

1. New HA install
2. Click through setup screen
3. Encounter error
...

### What version of Home Assistant Core has the issue?

2021.8.6

### In which browser are you experiencing the issue with?

Chrome 91.0.4472.114

### Which operating system are you using to run this browser?

RHEL 8.4

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
N/A
```

### Additional information

This error could be be caught and e.g. replace a "noname" value in place of abending.

**Comment by ludeeus** [comment]
Running Home Assistant Container as anything other than root is not supported.
